### ISSUE TITLE
refactor project

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/atom-project-viewer#10]
Been having too much bugs and commit fixes due to the fast growth of the package.
Will be refactoring all and properly add unit tests to minimise these issues.

Please create issues if you find any bugs.

**Comment by jccguimaraes** [comment]
this is still alive...

**Comment by jccguimaraes** [comment]
Have been making an approach on the package that I think it would be interesting to see how it flows.

**Comment by jccguimaraes** [comment]
Also, posted an entry on the Atom discussion about the future of this package [here](https://discuss.atom.io/t/future-of-project-viewer/26898/3).

A lot on my mind about this direction

**Comment by jccguimaraes** [comment]
There is also a discussion on **project-plus** https://github.com/mehcode/atom-project-plus/issues/36 regarding the direction of this and possible other packages.

**Comment by jccguimaraes** [comment]
latest update on the refactor.
Still a big mess but hope it will be a clean and performant at the end.

please comment and ideas for improvement

https://github.com/jccguimaraes/atom-project-viewer/tree/refactor

**Comment by jccguimaraes** [comment]
Hi all,
Can you give me feedback on the new idea for adding items (clients, groups or projects)? Thankz

![pv_cgp_add](https://cloud.githubusercontent.com/assets/14871650/14903930/9633c66a-0d9c-11e6-9088-a94b5ee7cedf.gif)

**Comment by jccguimaraes** [comment]
As well as this

![pv_cgp_treeview](https://cloud.githubusercontent.com/assets/14871650/14904027/40c8d444-0d9d-11e6-894b-febbc46c768c.gif)

**Comment by camlafit** [comment]
Hi 

Second capture looks nice, with ergonomic evolve
Frist capture, I don't see. Actual interface with all vertical step looks enough. This proposition as tab looks more complicate.

As in these propositions, clients have same behavior than group, miss  an action to add a (sub)subgroup.

**Comment by skratchdot** [comment]
I think it's looking good!  I initially thought it might be cool to have shortcuts for creating new Clients/Groups on the "Project" tab, but that's overkill after thinking about it more.  My thought was to save a few UI interactions if you just want to create a new Project (with a new Client/Group at the same time)- but it's really not worth the effort (and risk for introducing bugs, etc).

**Comment by jccguimaraes** [comment]
@camlafit, the reason I did this aproach was to make it **look & feel** like Atom styleguides. There are no select / option component to my like in the current styles. And the native ones just seems out of place.
But I agree that they do the job.

@skratchdot, I am thinking of a statusbar on the panel with some shortcuts, but they will be for another time :)
Probably add some alerts / warning icons when there are some problems instead of the intrusive popups the plugin currently has. Are you okay with the new Add modal?

**Comment by jccguimaraes** [comment]
autoclose popups now :p

![pv_cgp_workflow](https://cloud.githubusercontent.com/assets/14871650/14915711/f192c8ce-0e0c-11e6-9c86-35b38c40c5a4.gif)

**Comment by skratchdot** [comment]
@jccguimaraes - definitely okay with it!!!  It looks great.  I only put that one comment about shortcuts because you asked for feedback (and it popped into my head).  I don't think those shortcuts are worth any time or effort though- only mentioned it because it was the first idea that popped into my head.

Keep up the good work!

**Comment by camlafit** [comment]
nice :)

**Comment by jccguimaraes** [comment]
really valuable input. thanks guys

**Comment by jccguimaraes** [comment]
![pv_cgp_01](https://cloud.githubusercontent.com/assets/14871650/15876484/8bfcbc5a-2d05-11e6-90c0-87a38020d78c.gif)
![pv_cgp_02](https://cloud.githubusercontent.com/assets/14871650/15876485/8c13a3b6-2d05-11e6-8f96-bb4ab8acfe9a.gif)

**Comment by camlafit** [comment]
Nice :)

**Comment by jccguimaraes** [comment]
it's almost done @camlafit ! :)
