### ISSUE TITLE
Colors lost when updating project settings

### ISSUE THREAD

**Issue by codeitco** [jccguimaraes/atom-project-viewer#100]
# ISSUE

Updating any existing project group removes any set color preference (back to default - uncolored state)

## Environment

Windows 10;
Atom 1.12.6 Stable;
Project Viewer 0.3.32

## Steps to reproduce

1) Click on any project group to select it
2) Right-click and choose update
3) Make a change to something such as the title, icon or path
4) Click "Update"
Any set color should be removed from the project group and all children.

If no color is set yet, set the color first, click update and then repeat the steps above.

**Comment by jccguimaraes** [comment]
hey @codeitco,
thanks for pointing this out, i will have a look at it and hopefully fix this quickly!

**Comment by codeitco** [comment]
Hey @jccguimaraes, Not sure if this will be helpful or not, but I just wanted to add that I noticed the color sticks if you remove and set it again on each group update.

**Comment by codeitco** [comment]
Since we are on the color issue, if I could also request having the option in the package settings to set the active project / header color? The green works, but it would be nice to have control over this as well.

**Comment by jccguimaraes** [comment]
@codeitco, missed the last comment, i can try to investigate on this sure :+1:

**Comment by jccguimaraes** [comment]
@codeitco version `0.3.35` fixes the color issue, please validate.
Will now try to make the feature possible.

**Comment by jccguimaraes** [comment]
@codeitco please refer to the #101 for the selected color

**Comment by codeitco** [comment]
YUP, CONFIRMED FIXED! Thanks for the fast action on this!
