### ISSUE TITLE
FEATURE: Custom selected color

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/atom-project-viewer#101]
Ability to customize the current selected project color

**Comment by jccguimaraes** [comment]
@codeitco please validate this also! Many thanks

**Comment by codeitco** [comment]
Works great! Thanks for adding! Can you also do the same for hover color? Sorry to be picky, but customization is king! ;)

**Comment by codeitco** [comment]
I also noticed you made the change for hiding icon descriptions and only showing icons. That's great idea but when that's enabled, any way to enlarge the icon preview as they are a bit hard to see?

**Comment by jccguimaraes** [comment]
1. will try to make it available for the hover color
2. i need to check if the icons don't loose shape (or find a nice font-size for it

**Comment by jccguimaraes** [comment]
@codeitco please validate version `0.3.39`.

**Comment by codeitco** [comment]
It works! Thanks! Can you please also have the hover color set to the header "Project Viewer"? It would make sense since that only turns green when hovering over the panel. The green seems out of place for my editor theme as a whole.

**Comment by jccguimaraes** [comment]
:running_man:

**Comment by egbradshaw** [comment]
Are you out for a run? lol. sorry I dont' know what you mean hehe

**Comment by jccguimaraes** [comment]
@egbradshaw no run! :smile: that was me going back to the plugin to add more customization (I lack of imagination sometimes)

**Comment by codeitco** [comment]
ohh ok hehee :) All good my friend.

**Comment by jccguimaraes** [comment]
@codeitco can you please validate this?

**Comment by codeitco** [comment]
Works great! Thanks for implementing! I may have more suggestions/ideas if your interested?

**Comment by jccguimaraes** [comment]
Of course @codeitco, and you are more than welcome to contribute!
