### ISSUE TITLE
Project paths added to an open project are lost after closing and reopening the project

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#103]
# ISSUE
Root folders added to an open project, either using the update project dialog or project manager's "Add Project Folder" action, are lost after closing and re-opening the project.

## Environment
- **OS**: macOS 10.12.1;
- **Atom**: 1.12.2;

## Steps

- right click on an existing project
- click "update"
- click "Add root paths:"
- select a folder not already in the project
- observe: new path appears in project
- close the project
- open the project
- observe: the added path is no longer in the project

**Comment by GreenGremlin** [comment]
I am able to add root paths if I close the project, add the path(s), and then re-open the project

**Comment by jccguimaraes** [comment]
hey @GreenGremlin,

Thanks for reporting this. Will investigate this!

**Comment by jccguimaraes** [comment]
@GreenGremlin can you please validate this?

**Comment by GreenGremlin** [comment]
How do I install the fix?

**Comment by jccguimaraes** [comment]
you just need to update the package, Atom notifies you of outdated packages

**Comment by GreenGremlin** [comment]
Ah, didn't realize you had pushed a release out. Yes, it is fixed for me, thank you!
