### ISSUE TITLE
Root paths should be left justified in the project dialog

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#104]
# ISSUE
Minor issue: When editing an existing project (and likely when creating a project), the list of root folders is center justified. They should be left justified.

## Environment
- **OS**: macOS 10.12.1;
- **Atom**: 1.12.2;

## Steps

- right click on an existing project
- click "update"
- observe: the root paths are center justified

**Comment by jccguimaraes** [comment]
hey @GreenGremlin again,

Will take a look at this UI issue.

Thanks.

Feel free to contribute also!

**Comment by jccguimaraes** [comment]
@GreenGremlin can you please validate this?
