### ISSUE TITLE
Project config being corrupted

### ISSUE THREAD

**Issue by philip-hodder** [jccguimaraes/atom-project-viewer#106]
# ISSUE
Project configuration files are being corrupted. It looks like it is adding the root path of the previous selected project to the current project. 

I've noticed that there have been two releases in quick succession today (0.3.40 and 0.3.41?). This has only happened since these were issued. 

This is a great plugin but this update has completely killed it - I switch between projects all the time. 

## Environment
- **OS**: Windows 7
- **Atom**: 1.12.7
- Any other particularity;

## Steps

Click on "Project A". Right click "Update..." - the root path is "C:\repos\A". 

Click on "Project B", Right click "Update..." - the root path is "C:\repos\B". 

Click on "Project A". Right click "Update..." - there are two root paths: "C:\repos\A" and "C:\repos\B"

**Comment by jccguimaraes** [comment]
hey sorry for this :( will try to fix it ASAP

**Comment by jccguimaraes** [comment]
@philip-hodder,

Once again, sorry for this, can you check on the `0.3.42` version? you will need to revert the paths config unfortunattly.

**Comment by philip-hodder** [comment]
Hi! Thanks for the quick fix! I'll have to check my work machine (with Windows 7) tomorrow, but it seems to be OK on my Mac right now.

**Comment by jccguimaraes** [comment]
cool @philip-hodder! let me know then

**Comment by philip-hodder** [comment]
Hi! Seems to be working fine on the Windows 7 machine. Thanks for the quick response!
