### ISSUE TITLE
Newly created projects don't get initially sorted alphabetically.

### ISSUE THREAD

**Issue by codeitco** [jccguimaraes/atom-project-viewer#107]
# ISSUE
Whenever you create a new project under a group that is set to sort the list alphabetically, the project gets added to the end of the list regardless of the setting and must be manually dragged into the proper position OR you have to switch temporarily to "position" sort and then back to "alphabetical" to move the new project into the right position in the list.

## Environment
- **OS**: Windows 10 Home
- **Atom**: 1.12.7

**Comment by jccguimaraes** [comment]
i think this will not be fixed until `1.0.0` version. this can take me a lot of time. but if you feel this is a MUST currently, i will allocate time to it

**Comment by codeitco** [comment]
@jccguimaraes, pal, its totally up to you. Its not vital at all to me, just wanted to put it on the bug list for whenever its convenient for you. As a workaround, I can easily drag new projects into the correct spot or just toggle the sort modes whenever I need to clean up the list.

I may actually consider helping but I'm just so busy right now with 2 young kids in my life and I'm normally only on a computer for work during the day. If time ever opens up a bit, I will surely look at contributing.

As a teaser, are you making any big changes for 1.0.0 in the planning? If you don't want to spoil, that's alright :)

**Comment by jccguimaraes** [comment]
talk to me in gitter or other chatapp if you want ;p
