### ISSUE TITLE
How to open last open project/file on restart

### ISSUE THREAD

**Issue by jaredreich** [jccguimaraes/atom-project-viewer#108]
Hi there, amazing work on this package.

Just curious, no matter what project I am working on, when I close and re-open Atom it always seems to fallback to the same project, not the one I was last working on.

Thanks for your help!

**Comment by jccguimaraes** [comment]
hey @jaredreich, sorry for this, it may be related to the new versions of atom, I know they changed a bit the workflow for projects.

Just be patient and thanks for the vote of confidence.

**Comment by jaredreich** [comment]
I'm on Atom 1.12.6

**Comment by jccguimaraes** [comment]
hummmm, need to investigate then! :/

**Comment by jccguimaraes** [comment]
i can replicate this, will investigate this more today

**Comment by jccguimaraes** [comment]
this is getting harder to get the workaround. :\

**Comment by jccguimaraes** [comment]
@jaredreich this has been fixed, will run some more tests, and try to add some more features / issues to the next release!
