### ISSUE TITLE
Performance Issue: config.projects.paths grows / dupe entries?

### ISSUE THREAD

**Issue by skratchdot** [jccguimaraes/atom-project-viewer#11]
If I edit my config to be:
```json

{
  "groups": [{
    "name": "Audio",
    "expanded": true
  }],
  "projects": [{
    "name": "Unpublished",
    "group": "Audio",
    "paths": {
      "/Users/myname/Projects/audio-cell": "{\"audio-cell\":{\"expanded\":false,\"entries\":{}}}",
      "/Users/myname/Projects/audio-ease": "{\"audio-ease\":{\"expanded\":false,\"entries\":{}}}"
    }
  }]
}
```

Then I start to use the program, my config will eventually look like:
```json
{
  "groups": [{
    "name": "Audio",
    "expanded": true
  }],
  "projects": [{
    "name": "Unpublished",
    "group": "Audio",
    "paths": {
      "/Users/myname/Projects/audio-cell": "{\"audio-cell\":{\"expanded\":false,\"entries\":{}}}",
      "/Users/myname/Projects/audio-ease": "{\"audio-cell\":{\"expanded\":false,\"entries\":{}},\"audio-ease\":{\"expanded\":false,\"entries\":{}}}"
    }
  }]
}
```
Notice that `projects.paths.1` contains `project.paths.0` and `projects.paths.1`.  This becomes a performance issue when I try to add 50 paths because `projects.paths.49` contains entries `projects.paths.0` - `projects.paths.49`.

Is there a reason for these dupe entries, or is this needed for some reason?

Thanks for the work on this btw.  I just found it, and it seems very useful.  I might try to dig into the code to see if I can make some changes...

**Comment by jccguimaraes** [comment]
hi @skratchdot,

thanks for the feedback.
I see your point here. Indeed I did not think about it. the value is a property from the tree view. didn't count with multiple paths though! I believe it will be a simple fix.

You can look at the code but you will find it poorly written. I have begun refactoring big time all the code, but be my guess! :)

More than happy to help and receive feedback.

**Comment by skratchdot** [comment]
@jccguimaraes - sounds good. Not sure when I'll get a chance to look at it.  I spent a little time searching `paths` and looking at the database.js helper file.  For the time being, I've just limited the amount of paths I'm specifying. Thanks again for creating the project.

**Comment by jccguimaraes** [comment]
@skratchdot you can quickly find it in the *lib/views/project-view.js* for ```saveStateOfProject```and ```setStateOfProject``` they get and set the state from the tree-view. Hope it helps.

Just remember that the views got a lot messy after a while, so i'm counting on the refactor to clean all the junk...

Also, I am trying to make MochaJS run as the Atom custom testing framework but so far no luck...

**Comment by skratchdot** [comment]
Thanks for the info. That helps out.  I was wondering about how to test atom plugins.  I still haven't created one, but have recently gave Atom another chance, and am starting to use it more often.  I'll need to read some atom plugin tutorials and see the best way to write unit tests and get code coverage reports.  Have recently been messing with karma, mocha, chai, istanbul, isparta, sinon - wondering how everything fits into the atom workflow- so I look forward to seeing what you figure out w/ regards to mocha.

**Comment by jccguimaraes** [comment]
I have mocha + chai + sinon + istanbul working just fine in the command line (the downside is that i don't have access to the atom package).
All runs smooth and running on nodeJS v4.1.1 (ES2015) not Babel (i don't wan't to use it in this project, as well as coffeescript...)
You can check the attachment file for the current group refactor (model)
[coverage-group.pdf](https://github.com/jccguimaraes/atom-project-viewer/files/41209/coverage-group.pdf)

**Comment by jccguimaraes** [comment]
hey @skratchdot!
finally had a change to look at this. made all the changes and also fixed some bug on multiple projects.
hope all goes well.
will release in a bit

**Comment by skratchdot** [comment]
@jccguimaraes - This is great!  Thanks for this great plugin and sorry I didn't have time to fix this myself.  It's been a busy month for me.

**Comment by jccguimaraes** [comment]
@skratchdot i know what you mean :p
