### ISSUE TITLE
Cannot filter project icons 

### ISSUE THREAD

**Issue by jan-vince** [jccguimaraes/atom-project-viewer#110]
With Atom 1.13.0 icon filter field throws ```Uncaught TypeError: Cannot read property 'buffer' of undefined``` error and icons are not filtered.

No problem to find icon by hand, but search was much faster :) 

Jan

----

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.42

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/jan.vince/.atom/packages/project-viewer/src/modal-create-component.js:239

TypeError: Cannot read property 'buffer' of undefined
    at pv-create-modal.sortIcons (/Users/jan.vince/.atom/packages/project-viewer/src/modal-create-component.js:239:36)
```

### Commands

```
     -0:26.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.5.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:14.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.2.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:03.6.0 project-viewer:elevate-project (span.branch-label)
```

**Comment by jccguimaraes** [comment]
hey @jan-vince, yeah this is because they updated the `octicons` version and i need to check it back again.

Sorry for not keeping up to date.

Will try my best  today or tomorrow...

**Comment by jan-vince** [comment]
Hi, no problem - just wanted to let you know!

**Comment by jccguimaraes** [comment]
today i will have a look at some other issues, at the end of the day this will be published
