### ISSUE TITLE
Question: what does `dev mode` do ?

### ISSUE THREAD

**Issue by dudeinthemirror** [jccguimaraes/atom-project-viewer#111]
![screen shot 2017-01-23 at 12 38 11 pm](https://cloud.githubusercontent.com/assets/981638/22221773/36cc30e4-e169-11e6-9716-89484f295768.png)

**Comment by jccguimaraes** [comment]
hey @dudeinthemirror,

Forgot to remove this in the UI, there was an option to open a project in devMode, but there is no public API to do this without a full reload / new Atom instance, so i removed that, but forgot the UI, will do a clean up though!

thanks for the checking

**Comment by dudeinthemirror** [comment]
no worries, thanks!
