### ISSUE TITLE
If a project is already open, switch to it rather than open a second instance

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#112]
# ISSUE
- open project A
- switch to project B (not necessary, but shows the desired end result)
- from Project Viewer, open project A again

expected:
Since project A is already open, it should be brought back to the front

actual:
A second instance of project A is open

You

## Environment
- macOS 10.12.3;
- 1.13.1;

**Comment by jccguimaraes** [comment]
hey @GreenGremlin, i assume you have the option of opening each project in it's new window right?

If so, this needs investigation because I really don't know how to get the list of instances right now.

But is a nice feedback, thanks

**Comment by jccguimaraes** [comment]
@GreenGremlin, this is fixed, let me try to fix some more issues so i can release another version.

**Comment by jccguimaraes** [comment]
please validate @GreenGremlin

**Comment by GreenGremlin** [comment]
I'm still not seeing the 1.0.13 in Atom

**Comment by jccguimaraes** [comment]
what version of atom you have?

**Comment by GreenGremlin** [comment]
1.15.0

**Comment by GreenGremlin** [comment]
Ah, it looks like I have a theme that has a deprecation warning holding me back from upgrading :\

**Comment by GreenGremlin** [comment]
I was able to confirm the fix, thanks!

**Comment by jccguimaraes** [comment]
cool :)
