### ISSUE TITLE
Lost project settings

### ISSUE THREAD

**Issue by pete-hotchkiss** [jccguimaraes/atom-project-viewer#116]
# ISSUE
Project settings have gone AWOL. Provide documentation for how to upgrade from previous setup

## Environment
- **OS**: Windws;
- **Atom**: 1.14.1;

## Steps
Installed latest version 1.0.1 and all project settings have been nuked :-1: Nothing in the right hand pane at all
 
![image](https://cloud.githubusercontent.com/assets/16895748/22888524/f2a79fb6-f1fd-11e6-8799-00db025f1ed0.png)

**Comment by jccguimaraes** [comment]
hey, i need to fix it. see #115 please

**Comment by jccguimaraes** [comment]
Please update to `1.0.3` sorry about this...

**Comment by jccguimaraes** [comment]
@pete-hotchkiss, any update?

**Comment by pete-hotchkiss** [comment]
Sorry - crazy afternoon. The utils > conversion trick worked a treat :+1:
