### ISSUE TITLE
Auto hide does not unhide on mouse-over

### ISSUE THREAD

**Issue by felddy** [jccguimaraes/atom-project-viewer#117]
# ISSUE
When selecting the "Sidebar auto hidding" setting the side bar collapses as expected.  On mouse-over it does not unhide.   Also "hiding" is spelled incorrectly in the settings page.

## Environment
- **OS**: Mac OS X 10.12.13: 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
- **Atom**: 1.15.0-beta1
- **project-viewer**: 1.0.3

## Steps

- enable "Sidebar auto hidding" in project-viewer settings 
- mouse-over collapsed project-viewer sidebar

**Comment by jccguimaraes** [comment]
@felddy i can confirm this, will fix it sorry

**Comment by jccguimaraes** [comment]
will try to make a batch of latest errors

**Comment by felddy** [comment]
Confirming panel now hides as expected in 1.0.4.  Thank you for the quick response and fix.

**Comment by jccguimaraes** [comment]
#nice
