### ISSUE TITLE
Panel autohide doesn't work?

### ISSUE THREAD

**Issue by PixelT** [jccguimaraes/atom-project-viewer#120]
Hi - panel autohide in version > 1.0.x doesn't work as earlier?
If I check this option I have fadeIn / fadeOut the project list when I hover on panel
I expected, that on hover the whole panel will be show / hide, not only the items on it....

**Comment by jccguimaraes** [comment]
@PixelT hey, thanks for the feedback,

Can you make a screenshot?

If i activate the config the panel autohides not just the list, as well as I do the shortkey combination.

**Comment by PixelT** [comment]
http://recordit.co/RLtWPA7H9H
I hope now it's more clearly ;)

**Comment by jccguimaraes** [comment]
it is actually. you are using it on the lwft. need to validate classes :) thanks

**Comment by PixelT** [comment]
On right side this same situation :)

**Comment by jccguimaraes** [comment]
now you just killed me LOL

**Comment by jccguimaraes** [comment]
@PixelT what is the exact version you got? of the package?

**Comment by PixelT** [comment]
project-viewer - 1.0.5
atom - 1.14.1

**Comment by jccguimaraes** [comment]
@PixelT found the issue, just check the config `customWidth` and remove the value on it. or double click in the extreme (resizer) of the project-viewer main window then restart. I will be fixed.

It continues to be a bug and i will fix this ok?

Sorry

**Comment by jccguimaraes** [comment]
@PixelT can you validate this is working properly now?

**Comment by PixelT** [comment]
Seems to be work OK now :)
Thanks!

**Comment by PixelT** [comment]
But another "issue"
Earlier when I click right mouse on the panel I have options like: "Create group, create project, edit project / group" etc.
Now it is gone? :(

**Comment by jccguimaraes** [comment]
:( #122

**Comment by jccguimaraes** [comment]
hold on to your pants :smile:

**Comment by PixelT** [comment]
Oh I see, so I will be monitored it there 😄
