### ISSUE TITLE
How to add groups / projects !?

### ISSUE THREAD

**Issue by OhDerAlex** [jccguimaraes/atom-project-viewer#122]
Downloaded the newest project viewer files - and now the "right click" doesn't work anymore. How can I edit / add / delete groups and / or projects!?

**Comment by OhDerAlex** [comment]
ok found.. Menu Packages > Project-Viewer > Open editor...
but why no right click anymore? :(

**Comment by jccguimaraes** [comment]
will make it available @OhDerAlex! there is a shortkey also for now. sorry

**Comment by OhDerAlex** [comment]
Cool, thx.
And I like the changes - nice work!

**Comment by jccguimaraes** [comment]
been asked to implement an alike `open in finder / explorer`, what do you think? I still need to investigate this as well

**Comment by jccguimaraes** [comment]
@OhDerAlex next release will have feature back plus one more

**Comment by jccguimaraes** [comment]
@OhDerAlex check it on `1.0.7` release please

**Comment by OhDerAlex** [comment]
Hey. Updated now. Thanks a lot! :)
