### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by orkank** [jccguimaraes/atom-project-viewer#124]
# ISSUE
Can't create project or groups, Can't find utilities section.

## Environment
- **OS**: Macos Sierra;
- **Atom**: 1.14.2 x64;
- Any other particularity;

## Steps
1. Automatically updated from 0.3
2. All projects are gone
3. Restart, Alert messages
4. Can't find Utilities section
5. Uninstall complately
6. Reinstall but same issue

![atom](https://cloud.githubusercontent.com/assets/9553986/23012803/a0fa9d64-f430-11e6-9ff1-e3742271f7e5.png)

**Comment by jccguimaraes** [comment]
hey @orkank.

it ia like the notification says. you need to go to `packages - project viewer - utilities - convert 0.3.x`,

as for creating. for now you have `open editor`. i am getting context menu back up

**Comment by orkank** [comment]
There are no utilities in "Packages -> Project Viewer"

**Comment by jccguimaraes** [comment]
:scream: screenshot please. there should be

**Comment by orkank** [comment]
Oh I have fixed now, I was looking for Utilities in package settings 🤗  I've just checked the top menus 😣

Thank you for your interest.

**Comment by jccguimaraes** [comment]
no problem. it was a major version update
