### ISSUE TITLE
Folder structure keeps collapsing when switching projects

### ISSUE THREAD

**Issue by stephen-last** [jccguimaraes/atom-project-viewer#126]
# ISSUE
I've updated Project Viewer today to the latest version, and now the folder structure on the left keeps collapsing when switching between projects. This didn't happen before, and as I'm sure you can imagine, can be frustrating if you're working on files deep in a folder structure, and you're switching between projects.

## Environment
- **OS**: Windows 7 Pro;
- **Atom**: 1.14.3 ia32;
- **Project Viewer**: 1.0.9;

## Steps
I have the folder structure in the left panel, code/tabs in the middle panel, and project viewer in the right panel. If I open a few folders in the left panel so I can see the contents and/or open files, then click on a different project in the right panel (project viewer), then click back to first project again, the folder structure has been collapsed.

Don't know if this is related to an update to Atom or Project Viewer, as the folder structure is an Atom thing, but it happens when switching projects in Project Viewer.

This collapsing didn't happen before, it used to remember which folders were open when switching between projects.

### Note

Great work on this project BTW, it's so useful to be able to categorise projects into groups.

**Comment by jccguimaraes** [comment]
hey @stephen-last,

You are right, missed something in the new workflow. Thanks for pointing this out.

The last major refactor would be indeed on the context switching. A lot as changed in Atom's core, so i need to dig further. And sometimes it's going beyond the public API so there is always an inside debate if i should walk such paths. But hey, it's for the community!

Thanks for the last note :+1: really means something.

**Comment by jccguimaraes** [comment]
@stephen-last, please validate this

**Comment by stephen-last** [comment]
@jccguimaraes Hi, I don't think this is working... I've updated to the latest version (1.0.12) this morning.

If I have two projects listed in Project Viewer, I select the first one, open a folder in the tree view, then select the second one, and back again to the first, the folder has closed. The folder state (open) wasn't remembered when switching between projects.

I'm on Atom 1.15.0 now which is the latest version.

**Comment by jccguimaraes** [comment]
hummm, that is really weird. can you access the *devTools* and type `atom.packages.getActivePackage('tree-view')`?

**Comment by stephen-last** [comment]
Yep, i get this:

> Package {path: "C:\Users\stephen.last\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\tree-view", metadata: Object, packageManager: PackageManager, config: Config, styleManager: StyleManager…}

The object has lots of properties, is there something in there that might help..?

**Comment by jccguimaraes** [comment]
if you can debug the line `252` in `project-view.js` would be great because that should be good.

`devtools -> source -> cmd+o -> write project-view.js`

if that is too much is ok

**Comment by stephen-last** [comment]
I've taken a look, and in `C:\Users\stephen.last\.atom\packages\project-viewer\src\project-view.js` at line `251` it has your update code that starts `// hack to make tree-view update on project switching`.

[This code](https://github.com/jccguimaraes/atom-project-viewer/commit/734a08b3a34e93386e2922290a53456fea5aac76) is there...

I can't tell you anything about the code though, I've never done any Atom development before.

**Comment by jccguimaraes** [comment]
hummm this link is from a previous version. Are you sure you are running atom `1.1.15` and pv `1.0.12`? i know you said you are, although the code for tree-view is the same. it seems that it is not entering in the if condition. debug is easy, is just clicking on the line in the source

![pv_cgp_02](http://static.gitscout.com/d6cdab3c5f6d5ce7595b6c8550be884ed7b22e7a039096c7f20bbcd6c5ad7343.gif)

**Comment by stephen-last** [comment]
I'm not running Atom `1.1.15`, I'm running `1.15.0`, which Atom is telling me is the latest version. PV is `1.0.12` as shown in the settings under packages.

That's a cool amin you've sent. I can add a breakpoint, but I can't see the values when I hover over the variables like you can.

**Comment by stephen-last** [comment]
Ok... I'm getting the hang of this debug... When I click on a project, I see this:

![debug](https://cloud.githubusercontent.com/assets/16349203/24098479/6d143a5a-0d62-11e7-98db-072fa50e0d19.jpg)

**Comment by stephen-last** [comment]
`serialization` is `undefined`.

**Comment by jccguimaraes** [comment]
now we are getting somewhere :) you don't have serialization, which means, the context is not being saved, so if you go back and forward in projects, it will not do anything, can you check in the pv confs if you have checked `keepContext` or something like that?

**Comment by stephen-last** [comment]
Yes, I have `Keep Context` ticked...

![settings](https://cloud.githubusercontent.com/assets/16349203/24098625/56eb541a-0d63-11e7-8ed7-5a7f9eab6d78.jpg)

**Comment by jccguimaraes** [comment]
hummm, ok, so i found the issue here.
when you keep context, you ain't closing the current files opened PV just updates the tree-view files. PERIOD.

When you don't keep context, when you switch between projects, it will unload/load context to that project, including the tree-view state / scroll.

It's a bug, because i should save the tree-view state, scroll and width regarding the keep context.

I advise you, if this is not an issue for you, to untick the `keepContext` so that `tree-view` plays nicelly

Thanks for the value input @stephen-last. Really helped out in the troubleshooting.

**Comment by jccguimaraes** [comment]
no problem. i do this for the community :)

**Comment by jccguimaraes** [comment]
good news @stephen-last, fixed, i just need to validate more stuff regarding the breaking changes atom `1.17.0` introduced.

**Comment by jccguimaraes** [comment]
please check new version `1.1.0` and provide feedback if possible.
