### ISSUE TITLE
Panel is suddenly displaying inside the sidebar

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#127]
# ISSUE
Previously the Project Viewer panel was outside the sidebar, when placed on the left. With the latest update, it now displays inside the sidebar. It made more sense to have the project panel to the left of the sidebar.

## Environment
- **OS**: MacOS 10.12.3;
- **Atom**: 1.14.2;

## Steps
- update to Project Viewer 1.0.9
- set the panel to display on the left
- view the positioning of the panel.

**Comment by jccguimaraes** [comment]
there is two options for displaying left and right. that is last and first. please play around to see if feets your needs

**Comment by GreenGremlin** [comment]
Left now places it to the left of the editor, but to the right of the sidebar. Right places it to the right of both.

**Comment by GreenGremlin** [comment]
Ah, sorry. Left (first) does it. The option names are a bit confusing.

**Comment by jccguimaraes** [comment]
sorry mate.

Left (first) -> left of tree.view
Left (last) -> between tree.view and the editor
Right is indiferent if you dont have anything else.

if this not solve can you make screenshot? as i may not understand your point

**Comment by jccguimaraes** [comment]
:) not the best naming things :)
