### ISSUE TITLE
Project Viewer panel shows no projects

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#128]
After updating to 1.0.9, the panel shows no projects

![image](https://cloud.githubusercontent.com/assets/647452/23183495/1d651330-f831-11e6-8a06-64f4ca63984d.png)

I also see no projects when I use "shift-ctrl-alt-l: toggle the select list modal"

## Environment
- **OS**: MacOS 10.12.3 ;
- **Atom**: 1.14.2;
- **Project Viewer**: 1.0.9;

## Steps
See above

**Comment by GreenGremlin** [comment]
Here is what I see for the select list

![image](https://cloud.githubusercontent.com/assets/647452/23183675/bcb98182-f831-11e6-8e89-3f6b34511717.png)

**Comment by jccguimaraes** [comment]
hey,

there was a warning saying go to `Menu -> Packages -> Project Viewer -> Utilities -> Convert...`

this will convert the old to new

**Comment by GreenGremlin** [comment]
Ok, that fixed it. Thanks!

**Comment by jccguimaraes** [comment]
:)
