### ISSUE TITLE
Focus panel when collapsed does not open it

### ISSUE THREAD

**Issue by Hibryda** [jccguimaraes/atom-project-viewer#130]
I have project-viewer set to have panel auto hide. Unfortunately, when I press keys combination to focus on it, it focuses but does not unhide it. I suppose it's rather a bug. Or maybe I miss something.

**Comment by jccguimaraes** [comment]
sorry the delay, needed some break from the plugin, will try to investigate and have a solution!

**Comment by jccguimaraes** [comment]
@Hibryda, please validate this

**Comment by Hibryda** [comment]
Hi, can confirm it works as expected now (1.0.12). Thanks a lot.
