### ISSUE TITLE
autoHide join position: absolute;

### ISSUE THREAD

**Issue by rainjm** [jccguimaraes/atom-project-viewer#131]
Such as title

When the current project-viewer is displayed, the mini map of the window will shake.

E.g：https://atom.io/packages/autohide-tree-view

**Comment by jccguimaraes** [comment]
sorry the delay, needed some break from the plugin, will try to investigate and have a solution!

care to contribute?

**Comment by jccguimaraes** [comment]
@rainjm, been trying to make sense of this, can you please elaborate more on the subject?

Thanks

**Comment by rainjm** [comment]
- Want to [https://atom.io/packages/autohide-tree-view] this effect

- Show or hide the time does not affect the preparation of code area

- Because the occupation of part of the editor width will squeeze the code area, the visual sense of jitter

**Comment by jccguimaraes** [comment]
hey @rainjm, that makes sense thanks! will make it possible. thanks for the contribution

**Comment by jccguimaraes** [comment]
@rainjm, please validate this (through a config option)

**Comment by rainjm** [comment]
The trigger area is not close to the edge of the screen, and the edge of the screen gap, easy to move into the gap inside, the list disappeared

**Comment by jccguimaraes** [comment]
sorry @rainjm, but i didn't understand your point

**Comment by rainjm** [comment]
![kapture 2017-03-20 at 16 59 39](https://cloud.githubusercontent.com/assets/9592236/24093409/a3366942-0d8e-11e7-8bbe-8a6915616226.gif)
![kapture 2017-03-20 at 17 02 04](https://cloud.githubusercontent.com/assets/9592236/24093474/fa6b524a-0d8e-11e7-9db1-63685722ef3b.gif)


I am sorry, my english is poor
Look at the picture, there is a lacunae

**Comment by jccguimaraes** [comment]
@rainjm, thanks for this input, now i understand you :) will try to make this more UX friendly. :thumbs_up:

**Comment by jccguimaraes** [comment]
i believe #150 addresses this issue (not yet release)

**Comment by jccguimaraes** [comment]
please check new version `1.1.0` and provide feedback if possible.
