### ISSUE TITLE
Keyboard navigation not possible in new project/group creator

### ISSUE THREAD

**Issue by Hibryda** [jccguimaraes/atom-project-viewer#136]
As in title of this issue. TAB navigation (and any other actually) not working in this view. Also, as a side note, clicking "CREATE" before filling any fields raises error, while it should rather be not possible (disabled button).

**Comment by jccguimaraes** [comment]
@Hibryda is it ok for you not having the keyboard on the groups list?

**Comment by jccguimaraes** [comment]
please validate this issue!
