### ISSUE TITLE
Toggle project, linter-ui-default disappear

### ISSUE THREAD

**Issue by rainjm** [jccguimaraes/atom-project-viewer#137]
![kapture 2017-03-20 at 18 19 14](https://cloud.githubusercontent.com/assets/9592236/24095865/05ca88f8-0d9a-11e7-9ec8-7adf2b0cce04.gif)

Toggle project, [linter-ui-default](https://atom.io/packages/linter-ui-default) does not appear, disappear

**Comment by jccguimaraes** [comment]
yeah, this issue was fixed in `1.0.12`, can you confirm that it still happens?

**Comment by rainjm** [comment]
O, I did not update, thanks

**Comment by jccguimaraes** [comment]
:)

**Comment by jccguimaraes** [comment]
let me know if this is fixed
