### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by JasonSi** [jccguimaraes/atom-project-viewer#139]
[Enter steps to reproduce:]

Search an icon with a string like this 'foo\\', which is a word end with back slashes.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.12

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern

```
At /Users/jason/.atom/packages/project-viewer/src/editor-view.js:230

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at String.search (native)
    at /packages/project-viewer/src/editor-view.js:230:35
    at Array.forEach (native)
    at /packages/project-viewer/src/editor-view.js:228:37)
```

**Comment by jccguimaraes** [comment]
nice catch! :)

**Comment by jccguimaraes** [comment]
please validate

**Comment by JasonSi** [comment]
Looks great! Thank you.
