### ISSUE TITLE
Change group doesn't change project affectation

### ISSUE THREAD

**Issue by camlafit** [jccguimaraes/atom-project-viewer#14]
Hi

After a change group name , sub project weren't updated. Would be great to change group and move project to new group.
In my case, I've updated json configuration to change group name on each project.

**Comment by jccguimaraes** [comment]
hey @camlafit thanks for pointing it. it in fact should do that :\ will try fix it asap!
your setup? osx/linux/win?

**Comment by camlafit** [comment]
Hi

My setup : Debian Jessie / Gnome with atom 1.2.4 and project-viewer 0.2.23

Thanks

**Comment by camlafit** [comment]
yes ,  It's approved :)

Thanks a lot.

**Comment by jccguimaraes** [comment]
nice! :+1:
