### ISSUE TITLE
Error when creating a node without selecting a node type

### ISSUE THREAD

**Issue by Hammster** [jccguimaraes/atom-project-viewer#140]
When creating a new node and no type is selected you can still press `Create`, which creates a error. 

This should be handled or the `Type` selection radio should have a default selected. Also a little UX improvement 💪

**Comment by jccguimaraes** [comment]
did this help out?

https://github.com/jccguimaraes/atom-project-viewer/blob/929623ebb47264604662a28e6278620c98e71002/src/editor-view.js#L652

**Comment by Hammster** [comment]
Yep, but UX wise defaulting would be better. Or at least provide a small alert, so that the user knows what he forgot to set.

**Comment by jccguimaraes** [comment]
so you think it's best to make it default like to `project`?

**Comment by Hammster** [comment]
correct. then you have one click less for the default scenario.
Btw did you not had `create project` and `create group` in the context menu? Was there a reason to add the layer of the interface in between there? Or did you plan future use of the pane for a later expansion?

Sorry if I am bit nitpicky here 😸

**Comment by jccguimaraes** [comment]
hey @Hammster, sorry for late implementation. It's done now.

I didn't understand the last part "Was there..."

**Comment by Hammster** [comment]
Currently the steps are as followed

Right Click -> **Create New -> Select the Type** -> Fill Information -> Create

Before it was a little bit shorter

Right Click -> Create "**Type**" -> Fill Information -> Create

Was there a reason to do this ?

**Comment by jccguimaraes** [comment]
solo option for not having 2 menu items instead of just one... :D

**Comment by Hammster** [comment]
UX wise i would prefere to have two options, it feels a little bit artificial :P

Also no worries for the late responses, i am also stuck in a pile of work ;)

**Comment by jccguimaraes** [comment]
will try to add both then

**Comment by jccguimaraes** [comment]
done! will ship on next release. Taking the time to close some others I hope

**Comment by jccguimaraes** [comment]
please validate this issue!

**Comment by Hammster** [comment]
Great work, nothing to complain about 😄👍
