### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createView' of null

### ISSUE THREAD

**Issue by Duncank** [jccguimaraes/atom-project-viewer#142]
# ISSUE
When switching projects, the console opens with the following error:
> [path to atom]\.atom\packages\project-viewer\src\project-view.js:256 Uncaught TypeError: Cannot read property 'createView' of null

## Environment
- **OS**: Windows 10, 64 bit;
- **Atom**: 1.16.0;
- **Project Viewer**: 1.0.12
- I've also got the Seti-UI theme installed, which shows an error as well. However, when on the default Atom theme, this project viewer-error remains.

## Steps
Switch to another project.
![o16ind](https://cloud.githubusercontent.com/assets/719365/25063997/1015e15c-21f1-11e7-91c5-587aefce3730.jpg)

**Comment by jccguimaraes** [comment]
hey @Duncank, thanks for pointing this out, will fix this

**Comment by devnox** [comment]
When this will be fixed?

**Comment by jccguimaraes** [comment]
sorry @devnox, been fixing others, yeah will pick this today i hope

**Comment by jccguimaraes** [comment]
please validate

**Comment by Duncank** [comment]
No errors here anymore. Thanks for the quick fix!

**Comment by devnox** [comment]
Great! Thank you!  :)
