### ISSUE TITLE
Weird spacing next to project viewer

### ISSUE THREAD

**Issue by eduardomart** [jccguimaraes/atom-project-viewer#143]
# ISSUE
I have one project in my list that always has this weird padding next to the Project Viewer sliding drawer., see here:
![atom-weird-spacing](https://cloud.githubusercontent.com/assets/1833020/25204091/c0d49e1c-2510-11e7-82ce-e5cd7aa22c6c.gif)

## Environment
- macOS 10.12.4
- atom 1.16.0
- project viewer 1.0.12

## Steps
I even tried removing this one project and adding it again, but the strange padding re-appears. However, it doesn't seem to affect any other projects.

**Comment by jccguimaraes** [comment]
have you right clicked on it to see if it's an empty panel laying around?

**Comment by eduardomart** [comment]
right click will show me a "close tag" option, clicking on it doesn't do anything

![screen shot 2017-04-20 at 9 55 32 am](https://cloud.githubusercontent.com/assets/1833020/25242748/9b28afa6-25af-11e7-8e50-d0c82ad30cf3.png)

**Comment by jccguimaraes** [comment]
is this still showing after updating to Atom `1.17.2`?

**Comment by jccguimaraes** [comment]
closing this as no more feedback related to this
