### ISSUE TITLE
Enable/disable package per project

### ISSUE THREAD

**Issue by thomasfrobieter** [jccguimaraes/atom-project-viewer#147]
Hey guys,

can we add an option to enable / disable packages per project? 

**Example use case:** I have a lot of projects using sass-autocompile and remote-sync, while the new projects using gulp to solve those tasks. Sure thing.. those two solutions won't work well together.. so i need to turn off the plugins everytime i work on gulp projects.

It's similar to this https://github.com/danielbrodin/atom-project-manager/issues/265

**Comment by jccguimaraes** [comment]
@thomasfrobieter sorry foe the late reply. hell of couple of weeks.

That seems an interesting feature. need to dig more.

there are a couple of quesrions on my mind regarding this that could make the workflow complex.

let mw dwell a bit.

**Comment by jccguimaraes** [comment]
hey @thomasfrobieter, i have investigated around this, i believe there is an issue on atom itself saying for now it is not possible to disabled / enable package by project. What i mean is, i can make it possible but if you have multiple windows, it will disable on all of them, if you only use one window, i believe i can make this possible, i am introducing something similar in the next version.

Tell me your thoughts

Again.

*ex1* (different windows)
project 1 needs package_1 disabled
project 2 does not (but will have it)

*ex2* (same windows
project 1 needs package_1 disabled
project 2 does not (on context switch will be enabled)

**Comment by thomasfrobieter** [comment]
Hey @jccguimaraes, 
for me this is no problem! I do not have multiple Atom instances running at the same time.

Thank you so much! :)

**Comment by thomasfrobieter** [comment]
Just found this one: https://atom.io/packages/toggle-packages
Maybe it's helpfull.

**Comment by jccguimaraes** [comment]
will not develop more features in this package, a newer package will be released...
