### ISSUE TITLE
Keep content stop working o. 1.17.0

### ISSUE THREAD

**Issue by PixelT** [jccguimaraes/atom-project-viewer#148]
Keep content option stop working on 1.17.0 (when change project)

**Comment by jccguimaraes** [comment]
@PixelT this was a known bug on the beta channel, and the quick hack was to disable the context switching, i was hoping to have more time to work on a solution, but alas, they outrunned me... will try to give a solution fast! thanks for the heads up

**Comment by jccguimaraes** [comment]
@PixelT will send a more stable (i hope) for this in a bit

**Comment by jccguimaraes** [comment]
please check new version `1.1.0` and provide feedback if possible.
