### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by eliot-akira** [jccguimaraes/atom-project-viewer#149]
# Issue

Background: Upgraded Atom and project-viewer at the same time; lost previous projects (but not `project-viewer.json`); created new project..

When clicking on the project name, it won't open and displays the following error.

### Stack Trace

```
At ~/.atom/packages/project-viewer/src/status-bar.js:7

TypeError: Cannot read property 'getItem' of undefined
    at /packages/project-viewer/src/status-bar.js:7:30)
    at /packages/project-viewer/src/project-view.js:273:13)
    at /packages/project-viewer/src/project-view.js:19:8)
```

**Comment by jccguimaraes** [comment]
@eliot-akira thanks for reporting this.yeah atom `1.17` made a lot of breaking changes. not only on PV. i am activaly working on it. i hope during the next 24h to release a stable release.

**Comment by eliot-akira** [comment]
Thank you! Fortunately the project data was intact, so it wasn't a big problem. I appreciate the excellent work on project-viewer, I've been using it for a long time.

**Comment by PixelT** [comment]
After update to 1.1.0 I get this error when I try to change project... :(

**Comment by jccguimaraes** [comment]
can you try to clear all stored states files? in .atom/storage file? editor-whatever files

**Comment by PixelT** [comment]
I clear whole .atom/storage folder, but without any effects

**Comment by jccguimaraes** [comment]
ok. i will check on this. sorry about it

**Comment by jccguimaraes** [comment]
please validate with now @PixelT

**Comment by PixelT** [comment]
Unfortunatelly nothing change for me

**Comment by jccguimaraes** [comment]
can you share screenshots?

**Comment by PixelT** [comment]
http://www5.zippyshare.com/v/Wl1cFYXm/file.html
+ Stack Trace:
```
TypeError: Cannot read property 'getItem' of undefined
    at undefined._update [as update] (/Users/krzysiek/.atom/packages/project-viewer/src/status-bar.js:5:47)
    at project-viewer-project._openOnWorkspace [as openOnWorkspace] (/Users/krzysiek/.atom/packages/project-viewer/src/project-view.js:276:13)
    at project-viewer-project._onClickEvent (/Users/krzysiek/.atom/packages/project-viewer/src/project-view.js:17:8)
```

**Comment by jccguimaraes** [comment]
@PixelT, by bad, validate with `1.1.2` please

**Comment by PixelT** [comment]
From some reason I have status-bar disabled... 
After enaled it, seems to work OK :P

**Comment by jccguimaraes** [comment]
yeah, but that was an issue, i needed to validate if status-bar was enabled :)
also, there is an option that when you switch project, it tries to reload 3 default packages, and one of them is `status-bar` it could have been stuck in the process. If you keep having `status-bar` disabled, please inform me...

Thanks
