### ISSUE TITLE
Win10 - Separators issue

### ISSUE THREAD

**Issue by jas99** [jccguimaraes/atom-project-viewer#15]
PFA

Multiple sperators are showing up in Win10; let me know if you need more.

![screen](https://cloud.githubusercontent.com/assets/1231593/11698493/dc1b8180-9ee4-11e5-94b5-f3abf9206396.png)

Thx
Jas

**Comment by jccguimaraes** [comment]
thanks for the feedback. weird behaviour! will have a look at it.

**Comment by jccguimaraes** [comment]
i can't replicate this issue. can you give more intel on this? @jas99 thanks

**Comment by jas99** [comment]
@jccguimaraes Hey I have also stopped seeing this. So might be some weird thing. Will reopen this thread if I see it again.
thx :)
Jas

**Comment by jccguimaraes** [comment]
that's nice! :sunglasses: thx!
