### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by icimasa** [jccguimaraes/atom-project-viewer#153]
Try to open a project using atom-project-viewer and you get the uncaught error directly and no files or project is opened!

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.1.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:7

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at StorageFolder.module.exports.StorageFolder.pathForKey (~/AppData/Local/atom/app-1.17.2/resources/app/src/storage-folder.js:61:1)
    at StorageFolder.module.exports.StorageFolder.load (~/AppData/Local/atom/app-1.17.2/resources/app/src/storage-folder.js:42:1)
    at /packages/project-viewer/src/project-view.js:265:45)
    at /packages/project-viewer/src/project-view.js:17:8)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.7 
file-types 0.5.5 
git-plus 7.9.2 
highlight-selected 0.13.1 
language-cfml 0.17.0 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
package-sync 1.1.0 
project-viewer 1.1.2 
remote-sync 4.1.5 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by jccguimaraes** [comment]
sorry for the late reply. Been busy but will try to check this out soon.

thanks

**Comment by Miguel-F** [comment]
I am having this issue too.  None of my projects are opening now.

**Comment by jccguimaraes** [comment]
please validate this issue!

**Comment by icimasa** [comment]
Thx, for me this is working perfect now.. :)

great work

regards
Martin

**Comment by Miguel-F** [comment]
@jccguimaraes  thank you so much for taking the time to work on this issue!  I am no longer having this issue with the latest release.  Thanks!!!!
