### ISSUE TITLE
Open in new window doesn't work on first attempt (but it does when retrying)

### ISSUE THREAD

**Issue by rgawenda** [jccguimaraes/atom-project-viewer#157]
# Issue
In the project-view panel popup menu, open in new window does nothing at first attempt, but RMB again and retrying does work flawlessly.

## Environment
- **OS**: KDE neon 5.10;
- **Atom**: Atom 1.18.0 x64;

## Steps
1. Open the project-viewer pane
2. Open the popup menu clicking the right mouse button over a project
3. Select "Open in a new window" option
4. Nothing happens
5. Repeat steps 2 and 3
6. New window opens with selected project

**Comment by jccguimaraes** [comment]
thanks, will investigate this

**Comment by jccguimaraes** [comment]
confirmed this behavior :( will make a fix. thankz @rgawenda

**Comment by jccguimaraes** [comment]
please validate this issue!

**Comment by rgawenda** [comment]
It works like a charm. Thank you!
