### ISSUE TITLE
Migrate panel to dock

### ISSUE THREAD

**Issue by rgawenda** [jccguimaraes/atom-project-viewer#159]
It would be really great to have the project viewer integrated in the left dock as a tab. Wouldn't it?

**Comment by jccguimaraes** [comment]
there is work in progress around that, i think there is a config to make it a dock but it's pretty unstable

**Comment by jccguimaraes** [comment]
it's commented in the code, you can't change right now. sorry

**Comment by rgawenda** [comment]
Well, I've just activated the needed lines and asides from a little empty space it works nice!

**Comment by jccguimaraes** [comment]
@rgawenda cool! If you give it a go and see if no bugs arise. Care to make a MR?

**Comment by rgawenda** [comment]
I'm not really sure how to make a MR yet, but I can make a diff to see which lines I uncommented, some of them where blocking the package loading because a missing )

**Comment by jccguimaraes** [comment]
did you fork the project?

**Comment by rgawenda** [comment]
I've just done it, but forgot to create a branch. Quite new to git/guthub :grin:

**Comment by jccguimaraes** [comment]
thanks @rgawenda i am not finding time yet to review this sorry. Hope in a couple of days have.

Thank you so much for the PR by the way!

**Comment by jccguimaraes** [comment]
closing as this will be to the next major version.
