### ISSUE TITLE
Open the PV when clicking on status bar item

### ISSUE THREAD

**Issue by rgawenda** [jccguimaraes/atom-project-viewer#161]
# Feature Request
Most of the status bar items I'm currently using have some action for the click event, I think Project Viewer could activate from there.

**Comment by jccguimaraes** [comment]
should this open the `SelectList` view?

**Comment by rgawenda** [comment]
Ideally it would be an option in settings

**Comment by jccguimaraes** [comment]
will not develop more features in this package, a newer package will be released...
