### ISSUE TITLE
[Feature] When trying to initialize repo from Atom built-in Git integration pass currend project dir root to initialize

### ISSUE THREAD

**Issue by ethernal** [jccguimaraes/atom-project-viewer#162]
# Issue
Currently when trying to initialize the Git repo in Atom from built-in Git dock it shows user's default dir not the current folder for project. 

Expected:  When trying to initialize repo from Atom built-in Git integration pass currend project dir root to initialize

## Environment
- **OS**: Windows (7 and 10) x64
- **Atom**: 1.18;
- Trying to init repo on mapped server share

## Steps
1. Open a project (shared folder on the server)
2. Open Git Dock in Atom
3. Click "Create repository"

> and if possible provide a screenshot. :+1:
![image-init-repo-path](https://user-images.githubusercontent.com/714658/27728792-8fdb66c8-5d83-11e7-81c2-12991c6fa1df.png)

**Comment by jccguimaraes** [comment]
hey @ethernal, thanks for this feedback.
Will take a look at this :thinking:

**Comment by jccguimaraes** [comment]
hi @ethernal, sorry for late review on this issue, but open reading more carefully, I can't seem to identify any relation to this package.

Am I missing something? In the meanwhile I will close this issue.
