### ISSUE TITLE
Opening a project from the project viewer 

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#164]
# Issue
Opening an project from the sidebar causes multiple windows to open, all containing the selected project. It seems to happen wether the project is already open or not.

## Environment
- **OS**: MacOS 10.12.5 ;
- **Atom**: 1.18.0;

## Steps
- Open Atom
- Click a project in the project-viewer sidebar

![image](https://user-images.githubusercontent.com/647452/27979617-1c9bca00-632c-11e7-99e7-b99acd9c916d.png)

![image](https://user-images.githubusercontent.com/647452/27979629-352df8e0-632c-11e7-90d9-0b6d18d8a3ae.png)

**Comment by GreenGremlin** [comment]
After closing all open projects and starting from scratch, it looks like it is opening the project once for each open project. If no projects are open, it will not open at all. If two projects are open, it opens the new project twice.

**Comment by jccguimaraes** [comment]
hi @GreenGremlin, sorry for the late reply, been on holidays. i will have a look at this.

Thanks for sharing this issue.

**Comment by GreenGremlin** [comment]
I apologize for the rant, but this issue is so frustrating to deal with. Is there anything I can to to help expedite a fix?

**Comment by jccguimaraes** [comment]
hey @GreenGremlin, sorry for not being active on the fixes, been really busy at work. Let me try to find a time today to take a good look at this

sorry for any inconvenience

**Comment by jccguimaraes** [comment]
hey @GreenGremlin, i can't seem to replicate this issue. You are using the `1.2.0` correct?. Can you clear all files starting from `editor-*` in `~/.atom/storage` (keep in mind that it will clear all open files from each individual project.

If still occurs, can you please provide more intel?

**Comment by jccguimaraes** [comment]
ignore last comment, didn't see the `open in new window` set to true. confirm this is happening

**Comment by GreenGremlin** [comment]
Ah, yes! I can just disable `open in new window` for now, thanks!

**Comment by GreenGremlin** [comment]
This appears to be fixed in version 1.2.4!

**Comment by jccguimaraes** [comment]
nice!
