### ISSUE TITLE
Merge with Project Manager & Project Plus

### ISSUE THREAD

**Issue by mehcode** [jccguimaraes/atom-project-viewer#165]
@jccguimaraes We're planning a big project package and we'd love to have you and your contributors when we do. It'd be better for the community if we all work together.

See https://github.com/danielbrodin/atom-project-manager/issues/345

The general idea is a `project` package that defines a project service which contains the means to list, switch in (and out of window), etc. 

Then on top of that we would build out:
 - A `project-git` package that _provides_ git project discovery and provides metadata
 - A `project-manager` (replacing the existing) package that _consumes_ the project service and has a finder and some management utilities

Your team could build out a _consumer_ that replicates what you have here but:
 - _provides_ definitions of projects to the service from your db
 - _consumes_ the general project list to show the sidebar

This would allow:
 - When atom changes and in-window project switching breaks its updated in one place, the `project` package
 - A package such as `atom-build` could consume the `project` package to discover launch configurations. If the whole project management package ecosystem shared the core then other packages could build off of it.

**Comment by jccguimaraes** [comment]
hi @mehcode, this can be a good idea obviously.

Main condition would be to keep at least all the features `project-viewer` has at the moment.

We can talk about this in a more technical aspect as well as defining all very well.

how do you prefer to keep in touch for a daily basis talk?

**Comment by mehcode** [comment]
@jccguimaraes I'm on Atom's slack and that's convenient for me (as I always have Slack open) but I could be elsewhere (like IRC somewhere) if needed.

---

The primary thing you should decide is how married you are to the _how_ your package works (and not the functionality it provides).

 - The `project` package will define what a `Project` is and how you can interact with it.

 - The `project-manager` package will define a `projects.cson` file and consume individual `project.cson` files. This will also provide a select list view of all projects. 

If you want to integrate with just `project` you can keep 100% of how your package works and just change the very core. This would give you switching, etc. and the ability for users to install project providers like `project-git`.

If you want to integrate with `project-manager` then it seems what's unique about your package is the sidebar. You could write a `project-sidebar` package that works similar to your existing package.

**Comment by jccguimaraes** [comment]
closing. no further talking over this
