### ISSUE TITLE
[Feature] Items in .gitignore are not shown, but should be

### ISSUE THREAD

**Issue by audrummer15** [jccguimaraes/atom-project-viewer#167]
# Issue
Files that are placed in the .gitignore file of a project are not loaded in the project viewer. However, this is not always desirable. Sometimes, these files can be environment files that just don't need to make it out to a public git server.

## Suggestion
Make this functionality selectable via the preferences pane (possibly even down to each project)

**Comment by jccguimaraes** [comment]
hey @audrummer15,

never thought of this!
nice catch, i need to validate within Atom, if this is *native standard* behaviour, or something that can have a workaround (because this is dependant on Atom's state.

:+1:

**Comment by jccguimaraes** [comment]
will not develop more features in this package, a newer package will be released...
