### ISSUE TITLE
Open in a new window not working

### ISSUE THREAD

**Issue by faithlifechurch** [jccguimaraes/atom-project-viewer#169]
# Issue
First noticed in the latest update (1.2.1) – I am no longer able to right-click and select "Open in a new window." The context menu opens, but clicking does nothing.

<img width="378" alt="screen shot 2017-10-04 at 2 44 19 pm" src="https://user-images.githubusercontent.com/24554967/31193612-9dc59e9a-a912-11e7-9487-7ae73ad319ef.png">

The normal project switching works. I tried going into settings and enabling "Open in a new window," but that disabled project switching entirely. 

## Environment
- **OS**: MacOS 10.13
- **Atom**: 1.20.1

**Comment by jccguimaraes** [comment]
i was affraid something would break in light of disabling a feature :smile:

will do my best to fix that. sorry

**Comment by jccguimaraes** [comment]
please validate this issue @faithlifechurch
