### ISSUE TITLE
enabled after disable project viewer can't working unless restart atom

### ISSUE THREAD

**Issue by zsytssk** [jccguimaraes/atom-project-viewer#17]
I use atom projectmanager api to toggle project viewer;
it occur error when I disabled project viewer;
after this I enabled project viewer, it won't work;
![qq 20151214165737](https://cloud.githubusercontent.com/assets/2304648/11776673/eb440680-a283-11e5-8b03-e02404da5e6b.png)

**Comment by jccguimaraes** [comment]
this has something to do with the life cycle of the package. destroy should be optional though.
will investigate why this is happening.
thx
