### ISSUE TITLE
Open project in New window

### ISSUE THREAD

**Issue by pavelkraus** [jccguimaraes/atom-project-viewer#170]
# Issue
Description of the **issue**.

## Environment
- **OS**: OSX 10.9.5;
- **Atom**: last 1.21.0 x64;
- Any other particularity;

## Steps
HI, after the last update ( 1.2.1), the functionality to open the project into a new window stopped working. Nothing happens...
tnx Pavel

> and if possible provide a screenshot. :+1:

**Comment by jccguimaraes** [comment]
hi @pavelkraus, thanks for reporting this, i am trying to come up with a better solution, hope today to at least rollback the changes.

Thanks for the patient!

**Comment by jccguimaraes** [comment]
please validate this @pavelkraus

**Comment by pavelkraus** [comment]
Hi @jccguimaraes, now it's okay. (v1.2.2)
big tnx ;-)

**Comment by jccguimaraes** [comment]
cool :grinning:
