### ISSUE TITLE
I can not recover the panel after resize it to the edge of the window

### ISSUE THREAD

**Issue by aswasn** [jccguimaraes/atom-project-viewer#175]
# Issue
While I am writing something, the project viewer panel took up too much space so I dragged it to the right edge of the editor. Later I found that I can not drag it out...Once I move the cursor to the edge, I am only able to resize the whole atom window, I tried to re-install the package, but it didn't work. The project-viewer panel is still invisible.

What should I do?

(My suggestion is to add buttons to support fold/unfold the panel. Another "Reset" button to reset the size of the panel is necessary, too.)

## Environment
- **OS**: macOS High Sierra
- **Atom**: 1.21.0;

## Steps
1. open an atom window with project-viewer panel
2. drag the panel to the right edge of the window
3. now, project-viewer is unavailable!

**Comment by jccguimaraes** [comment]
hello @aswasn,

Please check settings `cmd+,` -> `packages` menu and search for the `project-viewer`. Somewhere along the many options you will find `Set a custom panel width`. Check if this is set to a lower value, default is `200`. Also check the `hot zone width` if you use `auto hiding`. If none of that helps, please shout again

**Comment by aswasn** [comment]
@jccguimaraes 
That works, thank you~

**Comment by jccguimaraes** [comment]
glad to help!
