### ISSUE TITLE
Getting a populated form when adding a project is confusing

### ISSUE THREAD

**Issue by GreenGremlin** [jccguimaraes/atom-project-viewer#179]
# Issue
As a user, it is confusing to select "New Project" and gets a form populated with the current project info. This behavior is confusing because it's not clear wether saving will create a new project or update the current project.

A better UX experience would be to allow a user to right click a project and select "Copy Project". The "New Project" form should always be empty. It would also help, for the copy project flow, if the form opened with the project name set to "Current Project Name (copy)", or something that makes it more obvious that you are not editing the current project.

**Comment by jccguimaraes** [comment]
it seems logic. thanks for the feedback

**Comment by jccguimaraes** [comment]
will not develop more features in this package, a newer package will be released...
