### ISSUE TITLE
use ctrl-alt-r to reload atom  window it don't reopen the latest open file  when project viewer is active

### ISSUE THREAD

**Issue by zsytssk** [jccguimaraes/atom-project-viewer#18]
use ctrl-alt-r to reload atom  window atom don't reopen the latest open file  when project viewer is active
I disable project viewer, It work

**Comment by jccguimaraes** [comment]
hi, can you specify more info no this? like you setup? win? is the file saved or unsaved?

thx

**Comment by zsytssk** [comment]
I startup atom, atom open lastest file when atom is close (status1)
and I close some file open some new file,(status 2)
use ctrl-alt-r reload atom 
atom don't recover status 2. it just recover status1

----

file is saved.
window 10
atom 1.3.1
install package:
-| atom-material-ui
-| autocomplete-paths
-| clipboard-plus
-| csscomb
-| emmet
-| expand-selection-to-quotes
-| expose
-| file-icons
-| jshint
-| minimap
-| project-folder
-| project-viewer

**Comment by zsytssk** [comment]
it work fine now. I dont kknow why

**Comment by jccguimaraes** [comment]
well if that continues to happen, just shout! thanks
