### ISSUE TITLE
Switching projects breaks Atom's GitHub integration

### ISSUE THREAD

**Issue by jcmarchi** [jccguimaraes/atom-project-viewer#181]
# Issue
When switching projects, it breaks Atom's GitHub's integration. The two UP and DOWN arrows (Pull and Push) disappear in most cases and only remain the UP arrow (but it stops working). The popup no longer appears when clicking the branch info and sometimes the entire bottom bar disappears.

## Environment
- **OS**: Linux;
- **Atom**: 1.21.1 x64;

## Steps
1. Create two or more projects.
2. Access one project that has Git in it and makes any change. Stage and commit it normally using Atom's GitHub window (CTRL+SHIT+9). The bottom bar will show the two arrows with a number near to the UP arrow, indicating there are committed changes waiting.
3. Switch projects by clicking on the Project-View list of projects.

Done. Your Atom's GitHub integration is now broken and probably one (or both) arrows are no longer visible. 

If you return the previous project, in certain cases, you may see the old "git changes" indicator, but no longer will be able to PULL or PUSH (or FETCH) anything because the pop-up no longer shows.

There is no need for a modification in the code for the Project-Viewer to break the Atom's GitHub integration. It only gets more visible if done as explained above (but it breaks regardless).

> and if possible provide a screenshot. :+1:

The Bottom Bar before it gets broken by the Project Switching:
![selection_060](https://user-images.githubusercontent.com/5833366/32636947-2b8679b4-c585-11e7-8454-ca58db2a2c7f.png)

The Bottom Bar after it gets broken by the Project Switching:
![selection_061](https://user-images.githubusercontent.com/5833366/32637018-7f828300-c585-11e7-8ad6-20e687845863.png)

As you can see, in this case, both arrows disappeared. As result, nothing shows when clicking on the branch name (a pop-up should show with Fetch, Pull and Push options for the arrows, and a branch switch for the branch name when you click on those). All gone.

**Comment by jccguimaraes** [comment]
Let me look at it. Thanks

**Comment by jcmarchi** [comment]
Sorry if I ask but... Any update? :)

**Comment by jccguimaraes** [comment]
Hi @jcmarchi, sorry for the delay, I have a working solution in the "younger brother" of **Project Viewer**, but at the moment I lack time to integrate the solution into this package.

At the very least in the beginning of Fev I will make the final adjustments.

I think contributing at the moment to this package is not the best thing.
I am not abandoning this project, just going through another way

**Comment by robhuska** [comment]
I too have this issue... Hoping for a solution soon. I switched from Project Manager because that one is even worse with bugs that have cropped up over the last several months with Atom updates.

Currently to fix this a reload of the window brings back all features that break when switching projects. This includes the file search #188.

**Comment by jccguimaraes** [comment]
Hi,
as I said on another issue

> hi @robhuska, really sorry for not releasing a more stable version. but the fact is that atom core changed a lot and just could not keep up with it. good news is that in Fev I intend to have a release. bad news is that until then I need the time off from Atom development

**Comment by robhuska** [comment]
Totally understand! Like I mentioned the workaround for now is to reload the Atom window when needed.

**Comment by jccguimaraes** [comment]
besides this release I plan to release PV younger brother... you can have it for a spin but its not release in atom as its still missing a lot of features  and it needs some manual set up...

**Comment by jccguimaraes** [comment]
@robhuska try now please

**Comment by robhuska** [comment]
@jccguimaraes the new release works great! Thank you very much.
