### ISSUE TITLE
project-viewer.json not being saved to when adding groups / projects via sidebar

### ISSUE THREAD

**Issue by Pathsofdesign** [jccguimaraes/atom-project-viewer#19]
Hey there, for some reason when I create groups / projects via the Project Viewer sidebar they don't persist to the project-viewer.json file so if I restart ATOM their no longer available. Any ideas? Thanks!

Atom 1.3.2
project-viewer 0.2.26

**Comment by jccguimaraes** [comment]
Hi @Pathsofdesign. Sorry for the late reply. Juat pinged on the emal now.

That is really weird.

Can you tell me your specs?
As well as if:
* You have multiple atoms opened (a recent bug @canatro found)
* json with no groups or projects?
* if you write directly on the json will they persist?

Will try to mimic that.

Thanks for the feedback

**Comment by Pathsofdesign** [comment]
Hey there! Thanks for the quick reply. I love this plugin but just started
having issues recently. I guess the only specs I know to tell you see the
ones I already have. I am using latest version of OS X El Capitan. I don't
have multiples Atom's open. I create a group first, then project, within
the projected viewer sidebar. Once I close atom and open it again my
projects are gone an

**Comment by jccguimaraes** [comment]
@Pathsofdesign you have same OS as I.
Recently added only the draggable option but i don't see how that can affect it.
But will try to recreate this issue. That's bad :( sorry.

Please be patient =)

**Comment by marionvdw** [comment]
Hi! I have the same issue… :(

**Comment by jccguimaraes** [comment]
sorry for the delay in the response and the why this can be happening, but I have been working all week out of my home country

**Comment by jccguimaraes** [comment]
@marionvdw and @Pathsofdesign can you expose here the structure of the `Packages -> Project Viewer -> Edit file` content?

**Comment by jccguimaraes** [comment]
```json
"groups": [
  {
    "name": "jccguimaraes",
    "icon": "icon-octoface",
    "expanded": true,
    "color": "#f9cc80"
  }
],
"projects": [
  {
    "name": "atom-project-viewer",
    "group": "jccguimaraes",
    "paths": {
      "/Users/joaoguimaraes/github/atom-project-viewer": "{\"atom-project-viewer\":{\"expanded\":true,\"entries\":{\".git\":{\"expanded\":false,\"entries\":{}},\"keymaps\":{\"expanded\":false,\"entries\":{}},\"lib\":{\"expanded\":true,\"entries\":{\"helpers\":{\"expanded\":true,\"entries\":{}},\"views\":{\"expanded\":false,\"entries\":{}}}},\"menus\":{\"expanded\":false,\"entries\":{}},\"node_modules\":{\"expanded\":false,\"entries\":{}},\"styles\":{\"expanded\":false,\"entries\":{}}}}}"
      },
    "buffers": [
      "/Users/joaoguimaraes/github/atom-project-viewer/lib/views/project-view.js"
    ]
  }
]
```

if something is wrong, you will have that error, example: `"groups"s: {...}`

**Comment by jccguimaraes** [comment]
do you any input on this @Pathsofdesign and @marionvdw.
thanks

**Comment by jccguimaraes** [comment]
so...
found the reason for the error.
new update should fix this.
the file should be wrapped in {}.
please confirm after update that this no longer occurs.

Thank you @Pathsofdesign and @marionvdw

**Comment by Pathsofdesign** [comment]
This has been fixed! thank you very much!

**Comment by jccguimaraes** [comment]
Glad it worked! Thanks

**Comment by marionvdw** [comment]
It works! Thank you very much!

**Comment by jccguimaraes** [comment]
good to know! :)
