### ISSUE TITLE
[Feature-request] sidebar animation delay setting

### ISSUE THREAD

**Issue by monkeydri** [jccguimaraes/atom-project-viewer#191]
I know there are many a lot of options and this package is already great but one little thing that annoys me is the delay for the sidebar animation on hover (when set to autohide).

Would be great if it was instantaneous, so a setting for animation delay below sidebar width would be awesome.

**Comment by jccguimaraes** [comment]
hey @monkeydri, thanks for the feedback. let me see if this is a quicky

**Comment by jccguimaraes** [comment]
check it out please

**Comment by monkeydri** [comment]
great ! thank you very much !
