### ISSUE TITLE
Atom keeping crashing after install package

### ISSUE THREAD

**Issue by horstmannmat** [jccguimaraes/atom-project-viewer#204]
# Issue
Once in a while atom ask to reload because it crashed;

## Environment
- **OS**:  4.20.7-arch1-1-ARCH 
- **Atom** : 1.34.0
- **Electron**: 3.1.3
- **Chrome**: 66.0.3359.181
- **Node**: 10.2.0

- Any other particularity;
Logs from atom:
`Attempting to call a function in a renderer window that has been closed or released.
Function provided here: background-tips-view.js:30:29
/usr/lib/electron/electron --type=renderer --enable-e[12713]: ../../vendor/node/src/fs_event_wrap.cc:91:static void node::(anonymous namespace)::FSEventWrap::GetInitialized(const FunctionCallbackInfo<v8::Value> &): Assertion `wrap != nullptr' failed.
 1: node::Abort() [/usr/lib/electron/libnode.so]
 2: 0x7efc7c898335 [/usr/lib/electron/libnode.so]
 3: 0x7efc7c88c900 [/usr/lib/electron/libnode.so]
 4: 0x7efc7c2411d0 [/usr/lib/electron/libnode.so]
 5: 0x7efc7c28ccaa [/usr/lib/electron/libnode.so]
 6: 0x7efc7c28c684 [/usr/lib/electron/libnode.so]
 7: 0x7efc7c1cb48f [/usr/lib/electron/libnode.so]
 8: v8::internal::Object::GetProperty(v8::internal::LookupIterator*) [/usr/lib/electron/libnode.so]
 9: 0x7efc7c631d47 [/usr/lib/electron/libnode.so]
10: 0x7efc7c638931 [/usr/lib/electron/libnode.so]
11: 0x20eb2c1842fd
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: background-tips-view.js:30:29
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: background-tips-view.js:30:29
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: background-tips-view.js:30:29

```

## Steps
- When I hover and right click on a group it crashes


> and if possible provide a screenshot. :+1:

**Comment by khartahk** [comment]
I'm having the same issue.

**Comment by fominv** [comment]
Same here, but not once in a while but every time i click on some project.

I have been using this package on my mac and it worked great, love it! Would be great if it worked on my Arch too.

**Comment by jccguimaraes** [comment]
sorry guys, it's been hard to keep up work with the needed updates. I don't know when, but I will try to not let you down. Thank you for using the package and loving it! That really means something to me.

🍻

**Comment by jccguimaraes** [comment]
hey all! is this issue still happening?

**Comment by horstmannmat** [comment]
As far as I tested, this issue is gone.


Thanks.

I will close it now, if it come back, I will open it again

**Comment by jccguimaraes** [comment]
bless you!
