### ISSUE TITLE
Custom order of groups/projects

### ISSUE THREAD

**Issue by canastro** [jccguimaraes/atom-project-viewer#21]
It would be nice to have the possibility of ordering the groups & projects by other order then alphabetic.

**Comment by jccguimaraes** [comment]
Thanks for the idea. Will implement this feature on the next version

**Comment by cedvan** [comment]
:+1:

**Comment by markvandenbrink** [comment]
It seems the custom ordering of projects and groups is working, but the list of clients is listed alphabetically. Is this correct and are you planning to implement custom (drag-and-drop) sorting for the list of clients? That would be great!

Thanks for all the hard work! Great package.

**Comment by jccguimaraes** [comment]
Hey @markvandenbrink, yes this is planned :)
You are correct, currently the clients is only working as alphabetically due to some implementations issue.
Please have patience :)

**Comment by jccguimaraes** [comment]
hey @markvandenbrink, will be releasing a new version with half of this issue fixed, will open a new one regarding only the 0 level in the tree.
