### ISSUE TITLE
Crash on macOS with atom >= 1.39.0

### ISSUE THREAD

**Issue by 7ute** [jccguimaraes/atom-project-viewer#213]
# Issue
The atom window crashes when interracting with the project-viewer bar.
Can be reproduced steadily on every atom version >= 1.39.0
(it does not seem to bug on atom 1.38.2)

## Environment
- **OS**: maxOS 10.12.6
- **Atom**: >= 1.39.0
- No crash without this plugin.

## Steps
- Click to toggle one folder (open/close, does not matter)
- Click again to select a project or toggle a folders ==> crash

> and if possible provide a screenshot. :+1:

A video to illustrate :
[![Alt text](https://7ute.fr/crash.png)](https://7ute.fr/crash.mp4)

The atom crash log associated with this crash
[atom-crash-log.txt](https://github.com/jccguimaraes/atom-project-viewer/files/3466590/atom-crash-log.txt)

**Comment by jccguimaraes** [comment]
hi @7ute, yeah, I have not maintained this project as I am focused on the new successor.
But this is breaking Atom, I will try to make a solution for this as well. Thanks for letting me know of it.

**Comment by jccguimaraes** [comment]
this has been resolved, will run some tests and deploy soon today

**Comment by jccguimaraes** [comment]
@7ute please validate

**Comment by 7ute** [comment]
Yup, that fixed it! 👍 
Thanks a lot!
