### ISSUE TITLE
FEATURE: Add keybinding for selecting project / status bar message

### ISSUE THREAD

**Issue by fireflyer95** [jccguimaraes/atom-project-viewer#22]
Like the package so far! Best project management package I have tried.

It would be nice to be able to set up keybindings for cycling between projects, something like next-project and previous-project, looping around from last to first and vice versa. I prefer working with keyboard over mouse, and it would be very smooth to switch between the projects that way.

Also, an indicator in the status bar of what project is currently selected would be most convenient (enabled/disabled in settings of course).

Thanks!

**Comment by jccguimaraes** [comment]
Hi @fireflyer95,
I am glad you find this package of use to you!
This could be a great feature for the next release!
Thanks for the feedback.

**Comment by cedvan** [comment]
:+1:

**Comment by jccguimaraes** [comment]
@fireflyer95 and @cedvan i know this is a long FEATURE, but half is implemented, just didn't managed to get in my head the right workflow for completing this.
