### ISSUE TITLE
Change the position of the panel

### ISSUE THREAD

**Issue by chuyik** [jccguimaraes/atom-project-viewer#24]
Could I change the position of the panel to the left, make it configurable?
Because I'm using a tool-bar button to toggle this project-viewer panel, and I wish they could all go to the edge left.

Here's the screenshot of my atom:

![image](https://cloud.githubusercontent.com/assets/6262943/12738845/64386ecc-c99f-11e5-87ff-d3c31dc75c8a.png)

**Comment by jccguimaraes** [comment]
Hi @chuyik, thanks for the feedback. Will make it happen :) well spotted

**Comment by jccguimaraes** [comment]
will make it available soon. :night_with_stars:

**Comment by jccguimaraes** [comment]
@chuyik did this suite your needs?

**Comment by chuyik** [comment]
@jccguimaraes Yes! Thanks for the quick action!

**Comment by jccguimaraes** [comment]
@chuyik no prob!
