### ISSUE TITLE
Create sub groups

### ISSUE THREAD

**Issue by cedvan** [jccguimaraes/atom-project-viewer#25]
Hi,

It's a very nice atom package. Manage project is awesome :)

it would be best able to create sub group :

- Client 1
    - Api
         - api-1
         - api-2
         - ....
    - Bundles
         - bundle-1
         - bundle-2
         - ....
    - Docker
         - docker-1
         - docker-2
         - ....
    - ... 
- Client 2
- Client 3
- ...

**Comment by jccguimaraes** [comment]
The thought as crossed my mind regarding an extra layer of nesting. I have been implemeting a refactor to the plugin so i can easely integrate more features.
But yeah, thanks for this input! :) and for enjoying the plugin. Really means a lot.

**Comment by vanboom** [comment]
:-1:  Keep it simple, the currently heirarchy is sufficient for everything that we do.

1. API-1
2. API-2
3. Docker-1
4. Docker-2
...

**Comment by jccguimaraes** [comment]
Hey @vanboom,
On the refactor, did manage to create a workflow from Client->Group->Project.
For me it's also sufficient to have G and P, but making it reach as much as everyone is my motivation for this project.
As said in other issue you comment, this refactor is taking way to long because i am changing everything and implementing all the cool features some pointed out.

So, does it make sense to keep as GP or CGP?
In terms of the sidebar it may be too much, but in terms of organization possibly the contrary.

**Comment by dtasic** [comment]
CGP would be great as long as there is still possibility to nest directly under Client. Sometimes I need group, sometimes I don't.

**Comment by jccguimaraes** [comment]
this can be complex but will try to make it happen. what are your thoughts? @dtasic @cedvan @vanboom 

```sh
| Client 1
    |--- Group 1
        |--- Project 1
    |--- Project 2
| Group 2
| Project 3
```

**Comment by camlafit** [comment]
Hi

Looks a great idea. In my use can be on same project I've theme, modules and some extra. In this case, mine projects are heavy. May sub group to split these project in more easy manipulation can be useful.

Looks nice to have group as node and project as leaf (group can be client, subproject, subgroup, ...)

**Comment by jccguimaraes** [comment]
hi @camlafit, @cedvan, @vanboom and @dtasic!

can you see the https://github.com/jccguimaraes/atom-project-viewer/issues/10 for feedback on this matter please?

**Comment by camlafit** [comment]
Hi

An another (real) case thinking 
Agency1 > ThierClients > Group > Project

Working as freelance on an agency, you can have at least two client level. In #10 interface propose "clients" as "group" behavior, looks sense to have any group level.

**Comment by jccguimaraes** [comment]
i see your point @camlafit.
But i think it will be hard to mantain a db / file struture for an _endless_ group level.
For now and not to delay any further the refactor, I will deploy as only CGP levels.

Hope you are okay with this
