### ISSUE TITLE
Feature request: autohide/hide on switching project

### ISSUE THREAD

**Issue by sjdawson** [jccguimaraes/atom-project-viewer#27]
A feature that I'd find helpful, would be if the project viewer panel could either autohide, or hide once you've switched to a new project.

**Comment by jccguimaraes** [comment]
hi @sjdawson
thanks for the suggestion, it has been implemented on the refactor. :)
don't know how long it will be out though, probably will merge this feature in the current version

**Comment by sjdawson** [comment]
Cool! :sunglasses: 

I look forward to seeing it when it hits. Great work! :+1:

**Comment by jccguimaraes** [comment]
Thanks 8)
