### ISSUE TITLE
Feature Request: Open and close Tabs

### ISSUE THREAD

**Issue by saivan** [jccguimaraes/atom-project-viewer#28]
It would be awesome if when we switched projects, we could save all of our current tabs and switch to the previously opened tabs of the project we are switching to.

For example, I have a project called <Master> and I'm working on master1.c, master2.js and master3.py. But there are 15 files inside of master (of which I've only opened 3).

I then switch to a different project called <Beast>. master1.c, master2.js and master3.py should close automatically, and atom will reopen beast1.c and beast2.c, which I was working on when I last switched out of <Beast>.

Then, when I switch back to <Master>, I will be greeted with master1.c, master2.js and master3.py again.
This would be awesome!

**Comment by jccguimaraes** [comment]
hi @saivan!
thanks for the input but the feature you are requestion already exists, you need to go the settings and enable the buffer thing :) currently is a bit buggy but on the refactor version will be a more mature workflow!
if that is not the case, please enlight me with more details on this.

**Comment by saivan** [comment]
Hello again. I have enabled this. But it seems that every time I switch projects, it only opens a single tab. It doesn't restore all of the tabs.

**Comment by jccguimaraes** [comment]
this has been improved and will be available on next release
