### ISSUE TITLE
Feature Request: Auto Opening

### ISSUE THREAD

**Issue by saivan** [jccguimaraes/atom-project-viewer#29]
When we type CMD+Shift+P, we get the context menu. It would be super cool if we could just go, open <Master> if we had a project called master somewhere in our project tree, and it immediately loaded. Would save time :)

Awesome plugin!!

**Comment by jccguimaraes** [comment]
hi again @saivan!
that would be nice indeed, will implement in the upcoming refactor (or path in the current one also)

**Comment by saivan** [comment]
Thats awesome to hear :)

**Comment by jccguimaraes** [comment]
hey @saivan,

could you please describe better what this means? it has been a while and need enlightenment on this again.

sorry

**Comment by jccguimaraes** [comment]
Closed due to no reply. Sorry
