### ISSUE TITLE
Default project name to folder name

### ISSUE THREAD

**Issue by ewoutp** [jccguimaraes/atom-project-viewer#3]
Adding a new project can be made quicker.
When adding a path, I would like the last part of the path to be used as default project name.

E.g. when adding path "/home/me/myproject" set project name to "myproject" (when it was empty).

**Comment by jccguimaraes** [comment]
thought about it! will make it happen! thankz for the heads up

**Comment by ewoutp** [comment]
Great!

**Comment by jccguimaraes** [comment]
Took a little while because the element atom-text-editor as an input has it's own behaviours. I am trying to finish the edit groups/projects and deploy with this feature. Don't know when though. I can commit now if you find it useful meanwhile. Cheers.

**Comment by ewoutp** [comment]
If it is an easy deployment, I would appreciate it.
Otherwise I'll wait.

**Comment by ewoutp** [comment]
Works great.
Thanks!

**Comment by jccguimaraes** [comment]
:+1:
