### ISSUE TITLE
Unable to complete a dialog with native-ui theme installed and active.

### ISSUE THREAD

**Issue by kjvandervalk** [jccguimaraes/atom-project-viewer#30]
Not sure if this is a problem with the theme or this package, but whenever native-ui is enabled I can only type in (for instance) the name of a group to add and select a color, but can't select a icon (list seems empty) and can't press 'Add group' or 'Cancel'.

**Comment by jccguimaraes** [comment]
hi @kjvandervalk 
thanks for reporting this out. will investigate and check if this is related to that theme or not!
will keep in touch

**Comment by dakrisis** [comment]
Hi @jccguimaraes,

this is my personal account. I will correspond through this one should you have any more questions :) I filled the issue out at work today, hence the other account. But thanks for taking this under investigation! 

At my workplace I develop on a Mac and got to updating it to El Capitan today. In doing so, I decided to test out the [native-ui](https://github.com/fv0/native-ui) theme, which only works proper with El Capitan.

I also decided to test out your project-viewer package at the same time. I get by editing the config file directly, but it's just a bit of weird behavior, that's all. It could very well be the theme that's to blame, switching to a Atom theme makes everything honkey-dorey, obviously.

**Comment by jccguimaraes** [comment]
@dakrisis :) 
Thanks for giving more inputs. It really seems to be from the native-ui but one never knows :D

**Comment by dakrisis** [comment]
I just found [this issue](https://github.com/fv0/native-ui/issues/27) in the closed section of native-ui. It seems the ::before element of the modal as styled by native-ui is the main offender. It seems to cover certain elements, making them unreachable.

**Comment by dakrisis** [comment]
The fact the ::before element is positioned absolute has some weird effects on the elements within the modal. Applying a position:relative on the inserted <div>'s (ie. add-group-view, remove-project-view etc.) remedies this issue and has no weird effects on a standard Atom theme.

My current fix in the user's `styles.less`:

`atom-panel-container.modal {
  div[is="add-project-view"],
  div[is="remove-project-view"],
  div[is="edit-project-view"],
  div[is="add-group-view"],
  div[is="edit-group-view"],
  div[is="remove-group-view"] {
    position: relative;
  }
}`

**Comment by jccguimaraes** [comment]
hey @dakrisis!
thanks for the investigation! wil try to patch it today!!!

**Comment by jccguimaraes** [comment]
@dakrisis please update the package :)
hope it works smooth

**Comment by dakrisis** [comment]
I already did this morning. Working smooth indeed. I will report an issue, with a reference to this one to the native-ui maintainer.
