### ISSUE TITLE
Toggle location

### ISSUE THREAD

**Issue by madvik** [jccguimaraes/atom-project-viewer#31]
Hello, 
Great plugin !
It is possible to locate the toggle of "project viewer" on the top of the present toggle with treeview ?
Thanks

**Comment by jccguimaraes** [comment]
Hi @madvik!

Can you elaborate a bit more on this?
Thanks

**Comment by madvik** [comment]
Like this : [http://imgur.com/4xNNh3a](http://imgur.com/4xNNh3a)
Thanks

**Comment by jccguimaraes** [comment]
I see your point, but i don't think there is a possibility for _splitting_ the tree-view vertically or horizontally, but will investigate for sure.
Meanwhile, there is an option to make it next to the tree-view instead of the other side...

**Comment by madvik** [comment]
Good idea !
Thank you

**Comment by jccguimaraes** [comment]
this is not an option for the moment, as there is no option natively to break panels in this matter, sorry
