### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by genezys** [jccguimaraes/atom-project-viewer#34]
Steps to reproduce:

1. Click on a project in the sidebar
2. Error!

**Atom Version**: 1.6.1
**System**: Debian GNU/Linux
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.31

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /home/vincent/.atom/packages/project-viewer/lib/views/project-view.js:123

TypeError: Cannot read property 'name' of undefined
    at saveStateOfProject (/home/vincent/.atom/packages/project-viewer/lib/views/project-view.js:123:44)
    at project-view.clickProject (/home/vincent/.atom/packages/project-viewer/lib/views/project-view.js:163:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "env-from-shell",
      "auto-run"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "project-viewer": {
    "startUp": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v2.3.0
file-icons, v1.6.20
git-log, v0.4.1
highlight-selected, v0.11.2
language-ansi, v1.1.1
language-docker, v1.1.6
language-haml, v0.23.15
language-nginx, v0.6.1
language-rspec, v0.5.0
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-haml, v1.2.0
linter-js-yaml, v1.2.5
linter-ruby, v1.2.2
make-executable, v0.1.1
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
pigments, v0.26.0
project-viewer, v0.2.31
quick-highlight, v0.3.10
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-syntax-replacer, v0.5.1
set-syntax, v0.3.0
symbol-gen, v1.0.0
symbols-tree-view, v0.11.0
sync-settings, v0.7.2
synced-sidebar, v0.4.3
terminal-plus, v0.14.5
trailing-spaces, v0.3.2
tree-view-git-branch, v0.1.2
tree-view-git-modified, v0.6.2

# Dev
No dev packages
```

**Comment by genezys** [comment]
Looks like the `directory` property cannot be found on an element of class `directory`. I do not know what this means since I could not find in code where the `directory` property should have been assigned.

**Comment by dtasic** [comment]
i had same problem. I tried to contract main projects folders in tree view. After that I was able to switch projects. Then again if I expand tree-view in some projects, error appears again.
I disabled "Tree-view-git-branch" that I had installed. After that it was working OK. See if it fix it for you.

**Comment by jccguimaraes** [comment]
hey @genezys and @dtasic,

thanks for pointing this out!
this can probably be because of that package, none the less, on the upcomming version, I have reworked everything and hopefully this external interfers won't happen!

Please have some patient :)

**Comment by genezys** [comment]
@dtasic Thanks for the workaround. Disabling the `tree-view-git-branch` package fixed my problem.

@jccguimaraes Happy to hear that.

**Comment by dtasic** [comment]
@jccguimaraes, nice to hear about upcoming version because this is best project manager I used so far. I tried Project Manager and Project Plus, but they all lacking clear UI that and ease of use that your package provide. Please keep working on it :)

**Comment by dtasic** [comment]
@genezys try tree-view-git-status, it does not break Project viewer, and it gives you current branch info in tree-view

**Comment by genezys** [comment]
@dtasic Thanks for the suggestion!

**Comment by jccguimaraes** [comment]
awesome @dtasic for suggestion an alternative!
Also thanks for the vote of confidence.

tell me something... what you think about this issue? #25 ?

**Comment by astucieuxzephyr** [comment]
@jccguimaraes I had the same problem and like @genezys and @dtasic , disabling the tree-view-git-branch package fixed the problem. A patch fixing this uncompatibility would be great, of course.
Anyway, thanks you for your awesome work on Project Viewer, I think it is the best project manager for atom until now !

**Comment by jccguimaraes** [comment]
@astucieuxzephyr, thanks once more for believing in the project, for some time I begun to wonder if I should continue development due to all the variations existing out there.

Again, the refactor is coming along on a new pace... still some major implementations missing but the rework on the **database** stuff had a big improvement.

**Comment by jccguimaraes** [comment]
@genezys, @dtasic and @astucieuxzephyr, closed rhis
