### ISSUE TITLE
Uncaught TypeError: Cannot read property 'realPath' of undefined

### ISSUE THREAD

**Issue by Wadjetz** [jccguimaraes/atom-project-viewer#35]
[Enter steps to reproduce below:]

1. Install nuclide IDE
2. Try to change the project

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.31

### Stack Trace

Uncaught TypeError: Cannot read property 'realPath' of undefined

```
At /Users/egor/.atom/packages/project-viewer/lib/views/project-view.js:158

TypeError: Cannot read property 'realPath' of undefined
    at project-view.clickProject (/Users/egor/.atom/packages/project-viewer/lib/views/project-view.js:158:59)
```

### Commands

```
     -7:57.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-gruvbox.theme-nucleus-dark-ui)
     -7:29.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.8.0 nuclide-side-bar:toggle (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-rust",
      "bookmarks",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-shellscript",
      "language-toml",
      "metrics",
      "racer",
      "linter-tslint",
      "vim-mode",
      "autocomplete-elixir",
      "tokamak-terminal",
      "tokamak",
      "tree-view"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".DS_Store",
      ".idea",
      "node_modules"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "nucleus-dark-ui",
      "gruvbox"
    ]
  },
  "project-viewer": {
    "startUp": true
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.8.0
autocomplete-paths, v1.0.2
editorconfig, v1.2.4
file-icons, v1.7.1
flow-ide, v1.0.6
gruvbox, v1.0.5
highlight-selected, v0.11.2
language-babel, v2.17.1
language-docker, v1.1.6
language-elixir, v0.12.3
language-hocon, v1.1.0
language-rust, v0.4.6
language-scala, v1.1.6
linter, v1.11.4
linter-eslint, v7.1.3
nucleus-dark-ui, v0.7.16
nuclide, v0.129.0
pigments, v0.26.0
project-viewer, v0.2.31
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
hey @Wadjetz,

thanks for reporting this!

**Comment by ericmuyser** [comment]
Hey just downloaded this and can't do anything with this bug :)

**Comment by jccguimaraes** [comment]
hi @ericmuyser,
will fix as soon as possible. was hoping it was a one time deal. sorry

**Comment by jccguimaraes** [comment]
this is due to having tree-view disabled.

**Comment by ericmuyser** [comment]
Hey @jccguimaraes!

Totally understand. Are you sure about that though? I think I have tree view enabled?

I updated and now clicking on the item highlights it, but does nothing. Ideas?

![image](https://cloud.githubusercontent.com/assets/156768/14582184/fe34e94a-03b2-11e6-9ac8-3a72b9ff1d37.png)

Cheers

**Comment by ericmuyser** [comment]
Sometimes it doesn't highlight it either

**Comment by ericmuyser** [comment]
Oh snap one of  my plugins is disabling tree-view and using a different one. I restarted, I re-enabled it *then* opened project viewer, and still no go.

![image](https://cloud.githubusercontent.com/assets/156768/14582212/86c268c8-03b3-11e6-8ff8-c88519773dc4.png)

**Comment by jccguimaraes** [comment]
so clicking the project wont open it right?
this has been fixed on the next major release. as it is is a bad hack i did :(

maybe a new release on the tree-view broke the hack.

working as fast as I can :(

**Comment by ericmuyser** [comment]
Oh sorry, I think I didn't understand how this was switching projects. I thought since I was adding a project it asked for a path that it meant it would open it for me. But looking at the code it looks like I need to add it to the tree view first? Is that right? It seems to be working now..

**Comment by ericmuyser** [comment]
I thought it would like open that folder in a new window... or switch to the window that had that folder open. I dont know if that's even possible though

**Comment by ericmuyser** [comment]
What if Atom loses the projects I added to the tree view? I dont want to go and add 30 folders back to it lol ideas?

**Comment by jccguimaraes** [comment]
You add root paths in the project add/edit mode/modal. You don't need to add in the tree-view.
You will definitly not loose the paths if you remove it in the tree-view.

The hack is just for the state of the expansion/collapsing of sub-folders.

The configuration is stored in a file in the atom root path.
I advise to you keep a backup of that file because it can loose the content if some crash occurs. (working on the fix also).

PV opens projects in the same window, not a new.

I may not be understanding what's happening to you. Can you elaborate on it?

Thanks

**Comment by ericmuyser** [comment]
Woah, it's suddenly working. It just wasn't opening anything when I clicked on it. Seem sall good now. Pretty sweet. Thanks @jccguimaraes !!

**Comment by jccguimaraes** [comment]
good to know! @ericmuyser. Hope you stick with PV 😃
