### ISSUE TITLE
Feature request: Project working sets

### ISSUE THREAD

**Issue by yucer** [jccguimaraes/atom-project-viewer#36]
It would be nice to have a third grouping level:

Groups -> Projects -> Working set

**Working sets** are a very nice feature of eclipse: http://bit.ly/1ps2hEE

If allows to define a set of folder and files to focus on a particular task. When a **Working set** is selected  the rest of the folders and files of the projects are hidden. 

Also in eclipse you can decide to show a group of working sets for a particular task, but even just having the possibility to select one would make easier to work with big projects using atom. 

I have seen many packages, and the one that is near to a nice implementation is this one.

The feature of hiding a set of folders and files is  present in this package: https://atom.io/packages/hide-files

**Comment by jccguimaraes** [comment]
hey @yucer,

This feature seems to come in handy in some situations yes.
I will add to my TODO list and hope I can deliever an equivalent solution.

But first need to investigate it :)

👍

**Comment by skratchdot** [comment]
@yucer - I use "groups" like I used to use "working sets" in Eclipse

**Comment by yucer** [comment]
Good idea, but there are some limitations. Yo have to enter the project directories again for the new group. Also you have to enter any of the folder do you use from this project as "projects". 

Sometimes you want the same folder structure in the project, just to hide many folders that don't apply to the current work.

But, in the case you need a workset of just one folder, yes it could do the trick.

**Comment by yucer** [comment]
As Eclipse uses it they don't have it in a hierarchy. 

They just have a list of projects and a list of working sets. In every working set you select a set of file and folders to show from all the projects. (It could be the case that a particular task need to focus just on two or three folders from some projects)

If no file is selected from a project, then the project is not shown. 

But maybe this is too much noise for this package. :-(

**Comment by yucer** [comment]
In order to you understand my problem. I include two images from a long project that I need to constantly scroll. Because most of the times I work with a subset of the addons (according to the task).

Every folder is an addon (a python module):

![longproject01](https://cloud.githubusercontent.com/assets/1835059/14762883/16d4de28-0986-11e6-96fc-8d86e4c29fd9.png)

The addons list is long here is the end:

![longproject02](https://cloud.githubusercontent.com/assets/1835059/14762882/16d3fecc-0986-11e6-8946-f539b6489a4c.png)

Yo can see the complete structure here: https://github.com/odoo/odoo

**Comment by jccguimaraes** [comment]
on the next release there will be a 3 level organisation. named clients/groups and projects. maybe they can fit your needs when it goes out and until i investigate your feature request

**Comment by yucer** [comment]
I have learned how to use it better.

Given that you keep the tabs open, I am now loading many sub-folders as projects and I can work with that.

It is by far the best package for project organization that I have seen in Atom.  :-)

Thank you very much.

**Comment by jccguimaraes** [comment]
and you haven't seen the next version :p

**Comment by jccguimaraes** [comment]
hi @yucer,
with the new version, this issue is still a _thing_ to you? Or can we close it?

**Comment by jccguimaraes** [comment]
Closed due to no reply. Sorry
