### ISSUE TITLE
FEATURE: Resizable panel

### ISSUE THREAD

**Issue by Getz85** [jccguimaraes/atom-project-viewer#37]
I don't know if this is possible, but it would be great if we could resize the project viewer panel; as what can be done on the tree view.

 Thanks for this awesome package!

**Comment by jccguimaraes** [comment]
that would be really cool! on the **TODO** 📖

**Comment by jccguimaraes** [comment]
@Hammster any luck?

**Comment by Hammster** [comment]
sadly i had no time left, but i'll assign it to me.

**Comment by codeitco** [comment]
Hey guys,

Any updates on the progress of this feature? I LOVE project viewer and plan to continue using it extensively but the tiny panel is making it harder lol :)

**Comment by jccguimaraes** [comment]
@hey @codeitco,

I will pick this up and try to make it released today!

**Comment by jccguimaraes** [comment]
@codeitco can you please validate this on `0.3.33` version?

**Comment by codeitco** [comment]
Hi,

Unfortunately its still doing this on 0.3.33.

Even just a simple group name change removes the color setting. Could it be
something related to the "Set Color" checkmark at the bottom of the dialog?
Whenever I make a change and hit update, the next time I open it, that
checkmark is no longer green and disabled which in theory could be why the
color is removed but that might also be happening as a result of the color
being reset to default I suppose.

If you need any further information from me, I would be happy to help. :)

**Comment by jccguimaraes** [comment]
@codeitco?!? wrong issue? :)

**Comment by codeitco** [comment]
WHOOPS! I obviously didn't read properly :( Sorry my friend, you can delete the unrelated comment or move it to my color issue if thats possible. Thx

**Comment by codeitco** [comment]
BTW, its working for me! The panel resizes nicely! Thanks so much for adding this feature!

**Comment by jccguimaraes** [comment]
no worries, although i think i have resolved this current one. can you validate?

**Comment by jccguimaraes** [comment]
cool

**Comment by Getz85** [comment]
Works perfectly, thanks!
