### ISSUE TITLE
Can't assign folder path on Chrome OS with Crouton

### ISSUE THREAD

**Issue by Duncank** [jccguimaraes/atom-project-viewer#40]
When creating a new project on my Chromebook running Linux via Crouton, I can't add an associated path to a project.
When I select a different folder, the default path stays in the input box. I'll have to create the project and edit the config-file manually to assign the correct path. After that it works like it should.

**Comment by jccguimaraes** [comment]
hey there. sorry for the delay. will check the behaviour in my environment. cannot test in yours but i guess it ain't from env.

**Comment by Duncank** [comment]
Thanks, if you need me to try something let me know!

**Comment by jccguimaraes** [comment]
Hi @Duncank, please can you describe better this issue?

What I understand:

1) Project create model opens
2) You add the first folder path (and it will automatically fill the input as the folder name for convenience)
3) You add another root path (this will not change the input).
4) Input will only change if it's empty and the folders is also empty.

Please give me a *walkthrough* on this.

Thanks

**Comment by Duncank** [comment]
1. Project Create model opens
2. I enter the project name and select a group
3. The associated path field is empty and I can't type in it, so I hit the "Add paths" button.
4. I select a folder or create one and select that, for example /home/duncan/testproject
5. Only /home/duncan shows up in the associated paths line

So now I need to save this new project, and edit the project viewer file to update the path to the correct one. Once again, it is possible this is due to how Crouton works on Chrome OS, maybe they do something weird to access the disk partitions used by Chrome OS or something.

**Comment by jccguimaraes** [comment]
sorry for not checking this in a fast way but just didn't manage to get the time to it. Please be patient. Will appreciate it.

**Comment by Duncank** [comment]
No worries, take your time! I know the workaround so I can do my work. Just trying to help you improve this.

**Comment by jccguimaraes** [comment]
haven't forgot you! tomorrow i will be releasing the new version, if you still use this plugin @Duncank, please give me feedback if this still occurs.
Thanks

**Comment by jccguimaraes** [comment]
please validate

**Comment by Duncank** [comment]
It took some time before Atom discovered the update on my ChromeOS, but I managed to install it just now.

The update does not seem to fix my problem, but I've found some more info that might clear things up, and make it easier for me in the mean time:

If I click "add a root path" and browse to the folder I want in the explorer window:
1. if I create a directory "test" and go into it and press "OK", the root path becomes "/home/duncan".
2. if I create a directory "test" and go back up and select the folder (not go into it) and press "OK", the root path becomes "/home/duncan/Downloads/atom/test". So that works.

**Comment by jccguimaraes** [comment]
hummmm, ok, that clears any doubts, really don't know if this is an OS problem, of not detecting the newly created folder. thanks, will investigate more

**Comment by Duncank** [comment]
it doesn't only happen with newly created folders, it also happens with existing folders. Once I go into the final folder I want to select, it doesn't add the right path. If I just select it in the folder list, it works.

**Comment by jccguimaraes** [comment]
Hi @Duncank,
Can you please try to mimic the behavior by `File -> Open...`? Could not replicate it on my machine :(

**Comment by Duncank** [comment]
I'm back at my Chromebook today so I could test this; 

When I open a folder that way it behaves the same, so I guess this is an Atom problem and not a plugin-problem. Sorry to bother you with this!

**Comment by jccguimaraes** [comment]
No problem @Duncank!
We never know what is the source right? Thanks once again for testing it.
Will close this.
