### ISSUE TITLE
Inclusion of devicons

### ISSUE THREAD

**Issue by Hammster** [jccguimaraes/atom-project-viewer#41]
Hi there,

Since 3.0 will give a Clients>Group>Projects folding, a wider set of icons would be awesome. Projects tend to be classified by their technology 

eg. Same Client. Website in Wordpress, admin tool in NodeJs, old Admin Tools in Python or Ruby.

[Devions ](https://github.com/vorillaz/devicons) are also used in a lot of other Atom plugins.

cheers ;)

**Comment by jccguimaraes** [comment]
this can came in handy yeah

**Comment by jccguimaraes** [comment]
how its currently implemented in `0.3.0`.

![screencast 2016-05-30 10-39-35](https://cloud.githubusercontent.com/assets/14871650/15645921/fab61722-2652-11e6-92b4-0e5d204f85e4.gif)
