### ISSUE TITLE
Feature Request: Option To Open In New Window

### ISSUE THREAD

**Issue by DamnedScholar** [jccguimaraes/atom-project-viewer#46]
When you open a project with Project Manager, it always spawns a new window. I imagine that this isn't always a desirable behavior, but sometimes it is. I've been using Atom as a general-purpose text editor, so I'm not infrequently in a directory that hasn't been added as a project. In this case, I want to be able to easily open a new window so that I don't lose my place in the first directory.

**Comment by jccguimaraes** [comment]
hi @DamnedScholar, really forgot that use case! Will do of course that option. Thanks for the feedback

**Comment by jccguimaraes** [comment]
@DamnedScholar, are you comfortable with a config option that makes all project open in a new window?

**Comment by DamnedScholar** [comment]
I'd be comfortable with that. It's the behavior I want most of the time.

I've noticed that there aren't many context menu items. What about an option to open in a new window or the same window (whichever you don't have set in the configs) in the context menu, as well as the default behavior on left click?

If I had to choose between the two, a context menu item would be preferable. I'm used to right-clicking to open links and files in new windows, anyway.

**Comment by jccguimaraes** [comment]
I agree with you. Will make the context option a thing. meanwhile `0.3.3` has an option in the config for opening in a new window

**Comment by DamnedScholar** [comment]
Sweet action. Thanks for this. The project viewer sidebar and the ability to add icons were enough for me to download the package, and I was prepared to get used to pressing `Ctrl-Shift-N` before opening a different project if I needed to, but being able to do that via the mouse doubles the speed of using that sidebar.

I've got the beginnings of an image-coding system going, with a Github fork for local versions of other people's code and a > for command-line things. Probably going to color them (which will be easy thanks to clear class names on the elements). Then I'll have colored icons on either side.

**Comment by jccguimaraes** [comment]
Forgot to document but please check the command `ctrl+alt+t`... ;p

**Comment by DamnedScholar** [comment]
That shortcut conflicts with the `toolbar:toggle` command on the [Tool Bar](https://atom.io/packages/tool-bar) package (which is really common) and also the `build:select-active-target` command on the [Build](https://atom.io/packages/build) package.

When the settings checkbox is clicked, a project *does* open in a new window, but the current window also changes to that project.

**Comment by DamnedScholar** [comment]
Also, I don't think the shortcut is important at all. The settings checkbox is enough, without adding more clutter and potential conflicts to the keybinding space.

**Comment by jccguimaraes** [comment]
i think i can have a context-menu by tomorrow. no ke-bindings! been working on it but just too damn tired...

**Comment by jccguimaraes** [comment]
meanwhile, `0.3.4` has changed the keybindings so it wont conflit with the packages you described.

**Comment by DamnedScholar** [comment]
Hey, I'm not in a hurry. I had even started browsing the code to see if I could grok it enough to add the functionality myself and was pleasantly surprised when you got on top of it so quickly. Take as much time as you think you need. :)

**Comment by jccguimaraes** [comment]
Hey @DamnedScholar, if you would like to make the changes I will be glad, just say and it's yours :)

**Comment by jccguimaraes** [comment]
"When the settings checkbox is clicked, a project does open in a new window, but the current window also changes to that project." this is fixed by the way. will go on the next release

**Comment by DamnedScholar** [comment]
I haven't gotten to the point where I understand the workings enough to do that. I'm pretty new to all this JS-as-desktop-code stuff. My background is almost exclusively in making other people's artistic whims display cleanly and efficiently at different browser sizes, with some dabbling in using JS and PHP to take relatively simple information and change how it's displayed according to basic rules. But I'm taking a look at everything, and if I see something that I can manage, I'll do it myself. :)

**Comment by jccguimaraes** [comment]
ok thanks, added you to the contributions because of your earlier PR. Just haven't got time yet to release it.

**Comment by jccguimaraes** [comment]
added the context-menu in `0.3.6`. Please validate if possible! Thanks

**Comment by DamnedScholar** [comment]
Works great for me both ways.

**Comment by jccguimaraes** [comment]
cool
