### ISSUE TITLE
Colors gone in Project Viewer

### ISSUE THREAD

**Issue by kleerkoat** [jccguimaraes/atom-project-viewer#49]
# ISSUE
Seems with the new update there isn't an option to color the groups. Minor issue but was nice to have.
Thank you.

## Environment
- **OS**: OSX
- **Atom**:1.8.0

**Comment by jccguimaraes** [comment]
Hi, yeah, this is not an issue, i have removed this from this version.
But will make it available again, just give me time to implement.

Also you are welcomed to *contribute to this project* 💪

**Comment by jccguimaraes** [comment]
sure @astucieuxzephyr.
I must be honest, i removed because it was a hack and buggy and I am investigating the documentation for a "better" way.
Sorry for this mates.

**Comment by jccguimaraes** [comment]
Not much left to reimplement this. bare with me

**Comment by jccguimaraes** [comment]
please validate this

**Comment by astucieuxzephyr** [comment]
It works ! Thank you very much !! :)
