### ISSUE TITLE
FEATURE: Cannot import multiple projects, when trying to create a project in a group

### ISSUE THREAD

**Issue by oxsav** [jccguimaraes/atom-project-viewer#50]
# ISSUE

Cannot import multiple projects, when trying to create a project in a group.

**Comment by jccguimaraes** [comment]
Thanks for opening an issue.
Will have a look at it.

*Are you interested in* **contributing** *to this project*? 💪

**Comment by jccguimaraes** [comment]
What you wanted is to instead of making the root paths in one project, create multiple projects with each root file added correct?

**Comment by jccguimaraes** [comment]
this is going to be implemented only on `0.4.0` version!
