### ISSUE TITLE
Updating an item removes the icon selection

### ISSUE THREAD

**Issue by DamnedScholar** [jccguimaraes/atom-project-viewer#52]
When I right-click on an item in the sidebar that has an icon and select `Update...`, then save without selecting an icon, the icon disappears. The icon appears to be selected, and if I click on it it deselects. If I want to preserve it, I have to click to deselect and then click to select again, then save.

**Comment by jccguimaraes** [comment]
Thanks for opening an issue.
Will have a look at it.

*Are you interested in* **contributing** *to this project* as well? 💪

**Comment by DamnedScholar** [comment]
Fixed by #53.
