### ISSUE TITLE
Disabled/enabled status does not change on update.

### ISSUE THREAD

**Issue by DamnedScholar** [jccguimaraes/atom-project-viewer#55]
When you add a project without a path, it is added as disabled (styled in dark grey, with a strikethrough, and a cursor that turns into a "do not enter" sign). If you then update the project and add a path, it continues to be disabled. Reloading the window will fix this (changing the state of the project to what it should be). This behavior also happens in reverse (so a project whose path has been removed does not become disabled until the package is re-initialized).

**Comment by DamnedScholar** [comment]
`list-item-component.js` (where `validate()` resides) can't be required in `utilities.js` because it invokes functions that (at that point) haven't been declared yet and the compiler balks.

Not sure whether it would be more effective to re-create `validate()` inside `updateItem()` (and suck up the duplication) or have the `if (changes.paths)` block send a signal that tells the sidebar to rerun `validate()` when an item is updated. Probably the latter.

**Comment by jccguimaraes** [comment]
Thanks for reporting this. Your feedback is being awsome

**Comment by jccguimaraes** [comment]
fixed :)

**Comment by DamnedScholar** [comment]
Works perfectly. Thanks. :)

**Comment by DamnedScholar** [comment]
The simplicity of the solution is pleasantly surprising. I feel like my JS noobishness is showing through, because I didn't notice that `itemView` was capable of that. Now I know.

**Comment by jccguimaraes** [comment]
why do you say that? Do you know how much time it took me to fix this? _"if (changes.paths) block send a signal that tells the sidebar to rerun validate() when an item is updated"_ you just pointed me to the right direction. You were capable of interpreting someone else's code and for me that's the most challenging part of being a developer, and this is JS.... :) so cheer up mate!

**Comment by DamnedScholar** [comment]
I say that because I was convinced that `itemView` just referred to the item itself and I didn't make the connection that it would also have access to the list item methods like `validate()`.

Interpreting code is easy as long as variable and function names are human-readable. I've always been able to take known vocabulary in unknown logical patterns and translate into whatever native pseudocode my brain thinks in. Sometimes it takes a lot of time iterations and following code back and forth across multiple files.

I don't mean to come off as if I'm mopey or putting myself down. I'm just rambling. I tend to over-explain things sometimes.

**Comment by jccguimaraes** [comment]
:D
