### ISSUE TITLE
PERF: More backup services?

### ISSUE THREAD

**Issue by DamnedScholar** [jccguimaraes/atom-project-viewer#57]
This is mostly a heads-up sort of thing and also a potential discussion topic. The Gist backup is great, I'm sure (I can't make private gists, so I can't test it), but different people have different preferences. I use [Pinboard](https://pinboard.in/api/) for most of my bookmarking and note-storing. Some might prefer Evernote or [Laverna](https://laverna.cc/) or other solutions. I plan on building a backup system for Pinboard, myself. I have no stake in the others, but this would be a good opportunity to talk about a broader backup system.

**Comment by jccguimaraes** [comment]
Hi, there has been an awareness about this on the gitter chat i believe, between me and @Hammster.

It would be nice to add some cloud services indeed. GoggleDrive would be one of the tops priority I believe.

**Comment by jccguimaraes** [comment]
hey @DamnedScholar! wanna investigate your pinboard api?

**Comment by jccguimaraes** [comment]
hey @DamnedScholar! wanna investigate your pinboard api?

**Comment by DamnedScholar** [comment]
Upon taking a closer look at the API, Pinboard isn't a good answer for me. It stores two types of objects, bookmarks and notes, but there is no public method to create a new note.

So it would probably be best for me to sync via Dropbox, then.

**Comment by jccguimaraes** [comment]
hummm, that's a shame :/ well, thanks for investigating it anyways. If you fill confortable on making the same for GD would be great! nice work mate

**Comment by DamnedScholar** [comment]
I'll figure out how to build a thing for whichever service I end up deciding on as the best way for me to save my projects. I'm in no real hurry and not in danger of data loss, but the lack of it is a challenge to be tackled when I finally resolve to do it.

**Comment by jccguimaraes** [comment]
:)

**Comment by jccguimaraes** [comment]
decided for just gist
