### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by reverdin** [jccguimaraes/atom-project-viewer#58]
# ISSUE
The backup only save once. Any other changes are not saved. 
The first backup create a private gist. If I add a project and backup again, the changes are not backed up. The gist has a new revision but whitout change.

## Environment
- **OS**: Mac OSX 10.11.5;
- **Atom**: 1.8.0;
- **project-viewer**: 0.3.10;

## Steps
Please try to describe **step by step** how to get to the issue.
1. Open Atom
2. Create a backup with project-viewer
3. Project viewer message: Successfully backed up the DB
4. The gist is created in github
5. Add a project to a group
6. Create a backup with project-viewer
7. Project viewer message: Successfully backed up the DB
8. A revision is created for the gist. This revision indicate "No change"
9. Import file with project-viewer
10. Project viewer message: Retrieved DB from Github successfully
11. The created project is gone and the restored db is the one cretaed in step 2

**Comment by reverdin** [comment]
Just did several others tests and found a way to make it work.

If I restart Atom before doing a backup, the changes are uploaded correctly.

**Comment by jccguimaraes** [comment]
hi @reverdin. so this option for saving to gist is trigged manually. the question is if the db is saving on creation.

it saves to db (not gist) on every action like collapse/expand. If you could be so kind and test this would be great.

will also investigate this as well as you are welcome to contribute!

It will not fetch from gist on reload open atom or leaving it

**Comment by jccguimaraes** [comment]
it will of course read from the db on reload.

**Comment by reverdin** [comment]
Thanks for your help and first of all thanks for this really useful plugin.

Tried the following steps:
1. Add a project.
2. collapse/expand some groups 
3. Toggle the project-viewer sidebar
4. Change the current project
5. File - Backup
6. The backed up revision is created in the gist but with no change
7. Quit Atom
8. Launch Atom
9. File - Backup
10. The backed up revision is created in the gist with the new project

I do not know how the db and saving is done but it is like if there is a working db which is saved on Atome exit and that it is the saved version which is sent to Github.

**Comment by jccguimaraes** [comment]
I am the one thabking you for liking and using this :)
i can only look at this in a few hours :/

**Comment by reverdin** [comment]
Am totally happy like that now. Just have to restart Atom before backing up.

I mainly use the backup to import sync my desktop and laptop projects....

Thanks again

**Comment by jccguimaraes** [comment]
just updated the project. can you please validate if this issue is solved?

**Comment by reverdin** [comment]
Hello,

Just did a test and the gist is created with the changes which is perfect.

Thanks for your quick release and have a nice week-end....

**Comment by jccguimaraes** [comment]
glad it's fixed xD. have a nice weekend too! take care
