### ISSUE TITLE
PERF: Ordering of level one items in PV tree

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/atom-project-viewer#61]
# ISSUE

Level 1 items in the PV tree are naturally alphabetically ordered / sorted.
## Environment
- **OS**: all;
- **Atom**: all;
## Steps

No steps

**Comment by jccguimaraes** [comment]
#21

**Comment by jccguimaraes** [comment]
This references to #21

**Comment by Pauan** [comment]
It is currently possible to manually reorder the top-level items.

Is this issue about *persisting* the ordering, rather than resetting to alphabetical on restart?

**Comment by jccguimaraes** [comment]
@Pauan 
This is a buggy behavior that i am reimplementing on the `0.4.0` version. I believe it would be an overhead of work for me to fix in the `0.3.x` version.

Sorry about that :cry:

**Comment by Pauan** [comment]
@jccguimaraes No worries, I was just wondering whether this was the right issue or whether I should file a new one. I don't mind waiting for 0.4.0

**Comment by jccguimaraes** [comment]
you wont regret it :laughing:
