### ISSUE TITLE
Uncaught TypeError: Cannot read property 'groups' of undefined

### ISSUE THREAD

**Issue by ghego1** [jccguimaraes/atom-project-viewer#62]
Failed Update
1. After auto-updating to 0.3.12 this error was thrown

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.12

### Stack Trace

Uncaught TypeError: Cannot read property 'groups' of undefined

```
At /Users/gherardo/.atom/packages/project-viewer/src/db.js:101

TypeError: Cannot read property 'groups' of undefined
    at content.groups.forEach (/Users/gherardo/.atom/packages/project-viewer/src/db.js:101:38)
    at Array.forEach (native)
    at Fs.readFile (/Users/gherardo/.atom/packages/project-viewer/src/db.js:92:36)
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

### Commands

```
     -0:55.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:37.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
angularjs-styleguide-snippets, v0.7.3
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
autoclose-html, v0.23.0
autocomplete-angular-material, v0.4.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
project-viewer, v0.3.12

# Dev
No dev packages
```

**Comment by DamnedScholar** [comment]
This might be a stupid question, but humor me. Errors sometimes happen when Atom updates a package, and then don't come back up when the package is activated on window start, so have you reopened Atom or at least forced a window reload since you updated?

**Comment by ghego1** [comment]
Yep, unfortunately after re-launching it came up this:

    Uncaught TypeError: Cannot read property 'groups' of undefined
    /Users/gherardo/.atom/packages/project-viewer/src/db.js:101    

Stack Trace:

    TypeError: Cannot read property 'groups' of undefined
        at content.groups.forEach (/Users/gherardo/.atom/packages/project-viewer/src/db.js:101:38)
        at Array.forEach (native)
        at Fs.readFile (/Users/gherardo/.atom/packages/project-viewer/src/db.js:92:36)
        at tryToString (fs.js:414:3)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

**Comment by DamnedScholar** [comment]
Okay, so `db.js:101` is in the function that reads data from the old storage scheme. Please go into the package settings and see if "Convert Old Data" is checked. If so, uncheck it and reload.

You could also try cloning the repo locally and then use `apm install` and `apm link -d` in the directory. That will set it up as a dev package and you can load it from the repo instead of your normal packages by opening a dev mode window. The `master` branch here is at the 0.3.12 release still, so there _should_ be no difference between the package you downloaded and the repo.

**Comment by ghego1** [comment]
Yep, worked :-)
Thanks!

**Comment by jccguimaraes** [comment]
hi @ghego1 and @DamnedScholar,

Thanks for the feedback and workaround respectively.
Ticking the check won't erase anything, at least that's not the intention...

You weren't getting any notification about the old file?

**Comment by webguywalker** [comment]
👍 , Working with latest update to 0.3.15
- projects moved gracefully, thank you.

**Comment by jccguimaraes** [comment]
:cool

**Comment by ghego1** [comment]
Great tks!
