### ISSUE TITLE
Possible icon redundancy

### ISSUE THREAD

**Issue by DamnedScholar** [jccguimaraes/atom-project-viewer#63]
`icon-eye` appears to be identical to `icon-eye-unwatch` and `icon-eye-watch`. Unless those eyecons are being addressed differently in the CSS, they should be folded into one.

**Comment by DamnedScholar** [comment]
Also redundant:

`icon-comment -> icon-comment-add`
`icon-git-branch -> icon-git-branch-create, icon-git-branch-delete`
`icon-git-pull-request -> icon-git-pull-request-abandoned`
`icon-lock -> icon-gist-private, icon-git-fork-private, icon-mirror-private`
`icon-file-binary, icon-file-text`
`icon-person -> icon-person-add, icon-person-follow`
`icon-plus -> icon-repo-create, icon-file-add`
`icon-repo -> icon-repo-delete`
`icon-repo-forked -> icon-gist-fork`
`icon-search -> icon-search-save`
`icon-star -> icon-star-add, icon-star-delete`
`icon-sync -> icon-repo-sync`

**Comment by jccguimaraes** [comment]
This is a good catch

**Comment by DamnedScholar** [comment]
This is resolved in #64.

**Comment by jccguimaraes** [comment]
Thanks dude!

**Comment by DamnedScholar** [comment]
No problem. It'll be nice having the icon list be a bit easier to navigate.

**Comment by jccguimaraes** [comment]
there were plans to just display the icon and add the _native_ notification on hover, what do you think?

**Comment by DamnedScholar** [comment]
I'm not sure I understand what you're describing. I don't recall a "native" notification.

**Comment by jccguimaraes** [comment]
my bad. just damn tired :) what I wanted to say was atom's native tooltip

**Comment by DamnedScholar** [comment]
Oh, for the name? It would definitely make the list shorter, but I've found myself navigating it partially based on the name of the icon. If there's one I'm looking for, I know if I'm close based on the alphabetical sorting. Maybe a config setting would be best, then the package can execute one loop or the other based on the user's display preferences.

**Comment by jccguimaraes** [comment]
yeah, my thoughts also on this. both and pros and cons, a settings would be more wise! Thanks.
