### ISSUE TITLE
FEATURE: Icons list

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/atom-project-viewer#66]
Add a setting option to switch icons list between `icon and text` and only `icon`.

**Comment by Hammster** [comment]
Is this relevant with the #70 pull request? If so, then we need to keep in mind that the filter requires content on the button element. Or we need to additionally filter the classes.

Otherwise i would like slightly bigger icons in the icon only list too.

**Comment by jccguimaraes** [comment]
This is a good question. In my opinion it will make it rich if an option for only showing icons without descriptions. We can see the impact on the filter (i think it's minimal), and yes. making icons bigger would be top (in this case).

**Comment by Hammster** [comment]
I am currently working on this, im gonne give you more input on gitter once i am home.

![bildschirmfoto 2016-09-01 um 17 55 49](https://cloud.githubusercontent.com/assets/1093709/18174337/798e6c70-706d-11e6-871a-a55cb339b59b.png)

**Comment by jccguimaraes** [comment]
hey @Hammster, this really looks Ace work.

**Comment by jccguimaraes** [comment]
[ ] make them bigger

**Comment by jccguimaraes** [comment]
@codeitco please validate version `0.3.39`.

**Comment by codeitco** [comment]
Awesome work! Looks great! Thanks so much!
