### ISSUE TITLE
Cannot read property 'addNode' of null

### ISSUE THREAD

**Issue by inssitu** [jccguimaraes/atom-project-viewer#69]
When I try to create a new group or project, appears a notification:

```
Project Viewer
Cannot read property 'addNode' of null
```

**Comment by jccguimaraes** [comment]
Thanks for opening an issue.
Will have a look at it.

*Are you interested in* **contributing** *to this project*? 💪

**Comment by jccguimaraes** [comment]
hey @inssitu, can you give more information on this please?

**Comment by Hammster** [comment]
I have the same issue but with "pathNotInArray is not defined".

I did create a project and it happens when adding a path, it happend on my mac and windows PC with the pulled version from github and apm.

**Comment by jccguimaraes** [comment]
`pathNotInArray` this is weird. Something wen't wrong. This does not exists but is checked in an if.

**Comment by Hammster** [comment]
Somehow this error did not occured anymore on my mashine after editing the project-viewer.json by hand.

**Comment by jccguimaraes** [comment]
so, `pathNotInArray` may have been a typo, will need to run some local tests to see if was only that. Thanks @Hammster for the feedback.

**Comment by jccguimaraes** [comment]
@inssitu can you please update the package and validate if this still occurs?
Thanks

**Comment by inssitu** [comment]
Thanks @jccguimaraes , it's working now :)
