### ISSUE TITLE
Expanded Project Folders

### ISSUE THREAD

**Issue by henryallsuch** [jccguimaraes/atom-project-viewer#7]
Is there a way to have projects open with their folders collapsed? I tend to have lots of project folders, so when I open a project it would be good if they were as so:

![screenshot 2015-11-03 11 06 18](https://cloud.githubusercontent.com/assets/889616/10915128/f3e99a18-821a-11e5-8d66-67eec0f28509.jpg)

Thanks!

**Comment by jccguimaraes** [comment]
Hi,
I have to look at the tree-view plugin if that's possible.
Thanks for the input!

**Comment by henryallsuch** [comment]
Sure! Thanks! I will also investigate.

**Comment by jccguimaraes** [comment]
working on a hacky stuff.

```js
JSON.stringify(document.querySelector('.tree-view').querySelectorAll('.project-root')[0].directory.expansionState)
```

this has a reference to all directories collapse/expand states.

need to make some tests

**Comment by jccguimaraes** [comment]
Hey @henryallsuch,
Just to make sure of one thing. When you say, "have project folders collapsed", you're saying the project root itself or it's children?

```sh
| root-project (collapsed)
```
or
```sh
| root-project (expanded)
| -- folder_1 (collapsed)
| -- folder_2 (collapsed)
```

Thanks

**Comment by henryallsuch** [comment]
Hello, I was hoping for the first example, as I often have multiple root folders, if it could remember previous state, that might be a easier or harder I am not sure.

```
| root-project (collapsed)
| root-project-2 (collapsed)
| root-project-3 (collapsed)
```
Thanks!

**Comment by jccguimaraes** [comment]
Hi,

Made it possible! Just finishing editing projects to commit recent changes.

:)

**Comment by henryallsuch** [comment]
Awesome!
