### ISSUE TITLE
Add new Project - 'pathNotInArray is not defined'

### ISSUE THREAD

**Issue by sjschmidt44** [jccguimaraes/atom-project-viewer#71]
# ISSUE
I created several groups yesterday, and added projects to each successfully. This morning I'm trying to add an additional project to a group, and am receiving an error: `pathNotInArray is not defined`. 

I've not changed any environmental settings, or added any additional packages to Atom since my last add to a group. This error is present regardless of the Group. I've restarted both Atom, and the computer. 

## Environment
- **OS**: Mac OSX, El Capitan;
- **Atom**: 1.8.0;

## Steps
1. Right click on a group name, and select `Update...`
2. Select the `add root paths:` option
3. Select the directory that I want to add to the group
4. Select the `update` button at the bottom of the pop-up
  - The pop-up does not close
  - The error shows in the top right of the screen:
```Project Viewer
pathNotInArray is not defined```

**Comment by Hammster** [comment]
Thank you for the report, we are aware of the issue and it is under investigation. It is somehow linked to #69, could you try to backup you project-viewer.json, delete it and restart atom.

no worries, you can replace it later on with your backup file.

**Comment by jccguimaraes** [comment]
so, `pathNotInArray` may have been a typo, will need to run some local tests to see if was only that. Thanks @Hammster for the feedback.

@sjschmidt44 will try to run your steps. thanks also.

**Comment by sjschmidt44** [comment]
Thanks for the quick responses!

Removing the `project-viewer.json` from the `menu/` dir (assuming you did not mean the `project-viewer.json` from the `keybindings/` dir), and then restarting Atom did not do the trick. 

The Groups and Projects are still listed in the tree view, but when I click on a Project to update, all I see is the option to `Open in New Window`.

I moved the file back to the `menu/` dir, restarted Atom, and the issue returned.

**Comment by Hammster** [comment]
@sjschmidt44 i was aiming for the file in the atom home dir `~/.atom/project-viewer.json`

**Comment by sjschmidt44** [comment]
@Hammster I don't have that file in the `~/.atom/` dir.

**Comment by Hammster** [comment]
oh my fault it should be under ` .atom\storage\project-viewer.json`

**Comment by sjschmidt44** [comment]
Removed that file from the dir, added a new Group and Project. The first group of paths that I added to the Project when I created were fine. When I went back to Update and add another path to that project it shot me the same `notInPath` error.

**Comment by Hammster** [comment]
Thank you for the feedback, the fix is on its way.

**Comment by jccguimaraes** [comment]
Please validate if this still occurs.
Your **feedback** is vital! 👌
Thanks in advance.

**Comment by sjschmidt44** [comment]
👍 All set here after update and restarting Atom. 

Thanks again for diving into this yesterday!
