### ISSUE TITLE
Bug: Can't remove project from client or group via the update modal

### ISSUE THREAD

**Issue by DamnedScholar** [jccguimaraes/atom-project-viewer#75]
Dragging a project out of its parent works, and selecting a new parent works, but if you deselect all parents, the project will not drop out of them. This applies to both clients and groups.

**Comment by jccguimaraes** [comment]
Thanks for finding this.
Will investigate.

**Comment by jccguimaraes** [comment]
Just release `0.3.26`. Can you check this out please?
