### ISSUE TITLE
ISSUE: Close my openned files when I switch the "context"

### ISSUE THREAD

**Issue by lneveu** [jccguimaraes/atom-project-viewer#76]
Hey @jccguimaraes !
First of all, thanks for this package! I use it every day since the first versions :+1: 
But since the 3.0 update (when you have refactored the clients/projects/groups management), the "behavior of contexts" has changed: now, when I switch between projects (or groups/project) all my files opened are closed :cry: (but conserved for the associated context). 

Do you plan to add an option to keep opened files even if we switch the context? It was a really usefull feature for me!

**Comment by DamnedScholar** [comment]
If you want to have multiple contexts open at the same time, there's the choice to open projects in a new window. If you right-click on a project, you will see the option, and you can go into the settings menu for the package to toggle that as the default behavior.

**Comment by LoannNeveu** [comment]
Thanks for the tips! But I would rather keep only one window like before.

**Comment by DamnedScholar** [comment]
I don't understand your use case. In what circumstances do you want to open multiple different projects in the same window? Wouldn't that force you to do a lot of extra work closing tabs? Is this something that can be solved by adding multiple root paths to a project?

**Comment by jccguimaraes** [comment]
hi @LoannNeveu, i know what you mean.
@DamnedScholar, previously you could simply switch between projects and only the tree-view package would be updated, keeping all files opened, even if they were from the previous project.

I don't see any problem in getting this old feature back.

**Comment by jccguimaraes** [comment]
@LoannNeveu just be patient. Did not have much time these couple of weeks and if it weren't for these great guys (@DamnedScholar and @Hammster) contributing to this package, a lot of the current work would not be yet out.

But tell me, do you like the new version (expect for this issue missing)?

Also, you are welcome to **contribute** as well!

**Comment by LoannNeveu** [comment]
Cool! Maybe if I find some free time, I will contribute to bring back this feature :smile: 
And, yes, I really like this new version!

**Comment by jccguimaraes** [comment]
@LoannNeveu, sorry for being so late in this feature, i must say, i forgot it :(

**Comment by LoannNeveu** [comment]
@jccguimaraes no problem! Me neither, I ran out of time :/

**Comment by jccguimaraes** [comment]
this is going to be implemented only on `0.4.0` version!

**Comment by LoannNeveu** [comment]
Thanks !! I am looking forward to it :+1:

**Comment by RemekConsulting** [comment]
Guys firstly thanks for the fantastic project tool. It has made using Atom work for me. Like Ineveu I also miss this old feature and would like to give one example where it has been particularly useful.

When I would like to copy a lot of code from one project to another, or compare two different versions of a file from two different projects, it was very handy to have them side by side in tabs. Yes, I realise that you can switch between two project windows, but this is a lot more visually disturbing than having two tabs and switching between them.

Look forward to the new version and really like some of the new features added recently, especially the clients option! Greg

**Comment by jccguimaraes** [comment]
So, version `1.0.0` is taking really damn to long to come out.
A lot of ideas, lots of changes, features, refactors, more refactors, delusions, a little more refactors, and just to little time to do it fast and good.

I am aiming this version to be THE last refactor one. More community friendly and fast-driven feature implementation.

It has grown so fast, atom changed a lot also.

Well, the point is, i am delaying fixing some issues on the current version, i am taking this nexts days to fix some important ones, i believe this feature is also important.

Thanks for the patient and believing in the package. I use it A LOT :)

**Comment by jccguimaraes** [comment]
Just release `0.3.26`. Can you check this out please?

**Comment by lneveu** [comment]
YEAH 🙏  At first sight all seem good 👍 I'll go back to you after checking this feature in depth.

**Comment by jccguimaraes** [comment]
any side effects here @lneveu?

**Comment by lneveu** [comment]
I'm experiencing many issues with the Atom new release (v1.12) 😢 (Git-diff is not working anymore, huge UI issues with my theme (seti-ui + vertical tabs), etc. Is it the same for you?)
But with project-viewer, all seems good 😄

**Comment by jccguimaraes** [comment]
I installed `seti-ui` and `vertical-tabs`. I think `seti-ui` is screwing everything right now. Don't forget that `>1.12.0` brings a lot of changes, specially in Electron and node. So it may have some issues until the guys from their packages fix/get up to date.

I personally don't use them and don't have any problems. `git-diff` seems to work fine, i use the terminal for git anyways

**Comment by jccguimaraes** [comment]
I will close this issue if you don't mind

**Comment by lneveu** [comment]
Thanks for your feedback! I'll try to re-install every packages.
Yep, you can close it.
