### ISSUE TITLE
FEATURE: Open project in dev mode

### ISSUE THREAD

**Issue by lexcast** [jccguimaraes/atom-project-viewer#77]
I would like to open certain projects in dev mode, but I don't know if this is currently possible.

**Comment by jccguimaraes** [comment]
Hi @lexcast.
This is something I haven't thought of but seems to be reasonably to do it.

Been of a little but will cary on the work.

**Comment by jccguimaraes** [comment]
hi @lexcast,

sorry for the late implementation of this, tomorrow morning will release new version with devMode option

**Comment by jccguimaraes** [comment]
can you confirm this? Thanks

**Comment by lexcast** [comment]
it works :tada: thanks
