### ISSUE TITLE
Edit Projects Manually

### ISSUE THREAD

**Issue by tujoworker** [jccguimaraes/atom-project-viewer#8]
Hi!

this project manager looks way better than all the others.
But I came across an issue I hope You find time to fix.

Once I Edit the file project-viewer.json - the projects/groups are not vissible in the sidebar:

![skjermbilde 2015-11-05 kl 21 28 21](https://cloud.githubusercontent.com/assets/1501870/10980813/4806c3d8-8404-11e5-9e9a-a1b4b69f596c.png)

When I then Add a new Group through the sidebar, the content of project-viewer.json gets overwritten bye the new group/projects.

Why?

**Comment by tujoworker** [comment]
My fault! I missed a coma in one path line. This fucks things up ...

**Comment by jccguimaraes** [comment]
thanks for the input thought.
well that failsafe if file "is corrupt" add the content from the the project viewer, can erase everything just for a simple missing coma... maybe i should remove that.

what do you think?

**Comment by tujoworker** [comment]
Leaving a different message than only an "empty" message would be good! - in case you can check that there is corrupt content in the file.
