### ISSUE TITLE
Open last project/file by default

### ISSUE THREAD

**Issue by scotthathaway** [jccguimaraes/atom-project-viewer#80]
# ISSUE
I switched from Project Manager to Project Viewer (you guys rock!).  I love several features, including groups of projects and the tree for selecting.  What I miss is Atom pulling up my last project and files by default.  Am I doing something wrong or is this feature not implemented?

Thanks,
Scott

**Comment by jccguimaraes** [comment]
hi @scotthathaway,

Thanks for the kind words about this plugin.
I should do what you are asking, but i myself am experiencing that when opening atom, the state is gone. I think it's due to the recent changes in atom and need to figure it out.

Please be patient!

**Comment by scotthathaway** [comment]
Ah.  Thanks for the fast reply!  I did not realize this was built in Atom functionality.  Hopefully Atom will get this fixed soon.

Scott

**Comment by jccguimaraes** [comment]
@scotthathaway can you confirm that you are still having this issues? If so, provide Atom version and plugin version, as well as steps to reproduce this.

Many thanks
