### ISSUE TITLE
Sidebar status is not remembered upon atom restart

### ISSUE THREAD

**Issue by gliviu** [jccguimaraes/atom-project-viewer#83]
## Environment
- Windows 10
- Atom 1.9.8

## Steps
* Hide project viewer sidebar
* Restart atom
* Project viewer sidebar still visible

**Comment by Hammster** [comment]
Thanks for your report, 

this is actually not a feature that we've implemented. You can check the settings you've probably have `startup Visibility` enabled.

@jccguimaraes maybe this could become a feature.

**Comment by jccguimaraes** [comment]
this was supposed to work actually! Will make the necessary fixes! 👊

**Comment by jccguimaraes** [comment]
well, got mixed up, actually, it it a feature that was not implemented nas @Hammster said.
@gliviu and @Hammster does it make sense to you that when `Toggle Sidebar` is activated, it will set/unset the `Startup Visibility`?

**Comment by gliviu** [comment]
My bad not checking that setting. However, @jccguimaraes I think it would make sense to link 'Startup visibility' and 'Toggle sidebar'.

**Comment by Hammster** [comment]
Maybe a good alternative would be a select (or radio)

- display on startup
- don't display on startup
- remember togglestate

This enables us more control over startup toggle state.

**Comment by gliviu** [comment]
with 'remember togglestate' being the default. Will have to be careful the first time app is open, the sidebar has to be shown considering no state is there yet.

As a user, the two approaches do not make too much difference for me. What is important is the sidebar to be visible the first time I install the extension and then remember its decision. If this happens, most probably I would never go into settings.

**Comment by jccguimaraes** [comment]
Thanks for the input!

**Comment by jccguimaraes** [comment]
will release this today or tomorrow

**Comment by jccguimaraes** [comment]
please validate :)

**Comment by Hammster** [comment]
It works, but is it really ok that it changes the user settings ? 

If i want the project viewer to be hidden on startup, i have to hide it manually before i close atom. Even if i unchecked "Startup Visibility". 

The togglestate should be saved as a separate variable not the setting value.

**Comment by jccguimaraes** [comment]
yeah, i was thinking on changing to another property. maybe this was not the best solution. will fix it later

**Comment by gliviu** [comment]
yes, persistence works fine now.

**Comment by jccguimaraes** [comment]
changed the config file in the last update. what do you all think?

**Comment by gliviu** [comment]
Perfect!! :)
