### ISSUE TITLE
Create project modal can't click create button if window height is not enough

### ISSUE THREAD

**Issue by ckentq** [jccguimaraes/atom-project-viewer#85]
# ISSUE
Description of the **issue**.

## Environment
- **OS**: mac 10.11.6;
- **Atom**: 1.10.0-beta7;
- window size: 1366 x 768;

## Steps
create a project -> create modal show.
the modal address too low, when adding project path, the create button is outside the window, and can't scroll modal content, so I can't really create any project

**Comment by jccguimaraes** [comment]
hi @ckentq,

can you please provide some screenshots? Also, which theme are you using.
thanks

**Comment by jccguimaraes** [comment]
closing as I don't have more information on this

**Comment by ckentq** [comment]
![-1](https://cloud.githubusercontent.com/assets/105282/19012613/54dc317c-87ed-11e6-931d-e1cd57af00b5.jpg)
Hi 
This is my screenshot,
main problem is
1. when open it, I cant' find a close button to close the modal.
2. create button is under the viviable screen area, and I cant' scroll down to click create or cancel button

thanks

**Comment by jccguimaraes** [comment]
Hi @ckentq, thanks for the feedback.
Will try to have a fix for this issue. Thanks

**Comment by jccguimaraes** [comment]
Please validate this issue @ckentq, it is not the best solution, but until `0.4.0` isn't out, it will have to work 👍
