### ISSUE TITLE
Don't override `atom.devMode`

### ISSUE THREAD

**Issue by jerone** [jccguimaraes/atom-project-viewer#87]
# ISSUE
On [multiple places](https://github.com/jccguimaraes/atom-project-viewer/search?utf8=%E2%9C%93&q=atom.devMode+%3D+&type=Code) in the code the internal property `atom.devMode` is overridden with new value. Please don't do this; this should be a read-only property only! Other packages depend on this property too.

## Environment
- **OS**: Windows
- **Atom**: 1.11.0-beta5

**Comment by jccguimaraes** [comment]
Sorry for thegitmagic, still wrapping my head around it's functionallity.

As we talked about, yeah this is not the best approach. will remove this hack until i have a decent alternative or not.

Also if you know of an alternative please share/contribute

**Comment by jerone** [comment]
[**@jccguimaraes**](https://github.com/jccguimaraes) commented on [23 sep. 2016 00:46 CEST](https://github.com/jccguimaraes/atom-project-viewer/issues/87#issuecomment-249050153 "2016-09-22T22:46:35Z - Replied by Github Reply Comments"):
> Also if you know of an alternative please share/contribute

What are trying to achive when overriding

**Comment by jerone** [comment]
[**@jccguimaraes**](https://github.com/jccguimaraes) commented on [23 sep. 2016 00:46 CEST](https://github.com/jccguimaraes/atom-project-viewer/issues/87#issuecomment-249050153 "2016-09-22T22:46:35Z - Replied by Github Reply Comments"):
> Also if you know of an alternative please share/contribute

What are trying to achive when overriding `atom.devMode` (here [1], [2], [3], [4])?

[1]: https://github.com/jccguimaraes/atom-project-viewer/blob/5b51bd82453e79ae9d96216fea922438b968a12a/src/list-item-component.js#L82
[2]: https://github.com/jccguimaraes/atom-project-viewer/blob/5b51bd82453e79ae9d96216fea922438b968a12a/src/modal-remove-quick-component.js#L33
[3]: https://github.com/jccguimaraes/atom-project-viewer/blob/5b51bd82453e79ae9d96216fea922438b968a12a/src/utilities.js#L121
[4]: https://github.com/jccguimaraes/atom-project-viewer/blob/5b51bd82453e79ae9d96216fea922438b968a12a/src/index.js#L166

**Comment by jccguimaraes** [comment]
hi @jerone, this is due to #77.

**Comment by jerone** [comment]
The only "correct" (read documented) way to open a project in devMode is [`atom.open({ devMode: true });`](https://atom.io/docs/api/v1.10.2/AtomEnvironment#instance-open).

**Comment by jccguimaraes** [comment]
I know. I will remove this action, or make it open in another window (which messes with one of the main features of this package). But as discussed in the Slack, it is a hack and should be off.

**Comment by jccguimaraes** [comment]
So, for now i have removed the hack, until a get (or not) a proper way. Thanks for the feedback @jerone and @lee-dohm.
