### ISSUE TITLE
Fix switching projects should not create a new pane

### ISSUE THREAD

**Issue by Pauan** [jccguimaraes/atom-project-viewer#88]
# ISSUE
When I switch from one project to another, it creates a new pane per project (each pane contains the tabs for that project):

http://i.imgur.com/lNzUTs0.png

In the above image, there are three projects open: `Scratch`, `node-server`, and `fable-view`. Each project is open as a separate pane.

I don't want this. When opening a project, I want it to replace the tabs in the existing pane, not create a new pane.

----

I also sometimes get this error:

http://i.imgur.com/gqDGs15.png

Maybe it's related.

## Environment
- **OS**: Linux debian 4.6.0-1-amd64 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux;
- **Atom**: 1.11.2;
- **atom-project-viewer**: 0.3.25;

## Steps
Please try to describe **step by step** how to get to the issue.

1) Switch from one project to another (by clicking on a project in the sidebar).

**Comment by jccguimaraes** [comment]
Hey, @Pauan,

Thanks for all the information you gave.
In fact it should not behave like this, it should in the way you want.
I don't have Linux installed and will try to check this out.

The error seems to be related.

**Comment by Pauan** [comment]
@jccguimaraes I just tried disabling all of my plugins and re-enabling them one-by-one. I found that the plugin which caused it to break is actually [ionide-fsharp](https://atom.io/packages/ionide-fsharp)! After disabling `ionide-fsharp`, everything works great! Thanks for creating such a great plugin.

I don't know why `ionide-fsharp` would cause it to break, but it's probably not the fault of `atom-project-view`, so I'm going to close this issue. I'm sorry for wasting your time.

**Comment by jccguimaraes** [comment]
@Pauan, this is actually interesting.
I will take a look at that package to see what it does!
You haven't wasted anyone's time and I am glad it's not from here.

Thanks for the feedback on the plugin itself. If you have any suggestions or want to contribute just give me a shout.

Take care

**Comment by Pauan** [comment]
@jccguimaraes If you still want to investigate this further, here are the steps that should reproduce the problem:

1) Install `ionide-fsharp` and `atom-project-viewer`

2) Restart Atom

3) `git clone https://github.com/Pauan/fable-getting-started`

4) Open `fable-getting-started` as a project in `atom-project-viewer`

5) Open a second project in `atom-project-viewer` (it doesn't matter what it is)

6) In the `fable-getting-started` project, open a `.fs` file (such as `src/fs/Main.fs`)

7) Switch to the second project

8) Switch back to the `fable-getting-started` project
