### ISSUE TITLE
FEATURE: Add fuzzy project search

### ISSUE THREAD

**Issue by ackerdev** [jccguimaraes/atom-project-viewer#89]
It would be extremely convenient if the project search used fuzzy matching.

Currently I have to be conscious of whether the project I'm looking for has a camelCased name, or dashes, or underscores, and if I have multiple projects with similar prefixes I have to type the entire prefix to be able to filter down via text. If the search was fuzzy, it would make switching to projects even faster and easier and make it easier especially when I don't remember the format of the project name (which I try to keep consistent with the source naming, though I could rename it however I want to match convention).

If you aren't already aware, atom's fuzzy search implementation is available https://github.com/atom/fuzzaldrin

**Comment by jccguimaraes** [comment]
hi @ackerdev,

Thanks for this feedback!
That could be a really nice feature to implement indeed.

I am currently working on the new version, so i think i will add it to `0.4.0` if you don't mind.

If you wish to contribute you are welcome!

Is this ok for you?

**Comment by jccguimaraes** [comment]
@ackerdev can you please validate this issue after the MR from @lneveu?

Thanks

**Comment by ackerdev** [comment]
@jccguimaraes #97 didn't add what I'm talking about here. It made the search case insensitive, which is a good thing, but not quite the same as fuzzy searching. A fuzzy search would allow me to type `foobar` to search for a project named `foo-and-bar`.

**Comment by jccguimaraes** [comment]
@lneveu you want to take a look at this?

**Comment by lneveu** [comment]
I'll look at that as soon as I can!

**Comment by jccguimaraes** [comment]
@ackerdev hope this has fixed!

**Comment by ackerdev** [comment]
Yep, this is fixed! Thanks & great work!
