### ISSUE TITLE
FEATURE: Clear project search after selection

### ISSUE THREAD

**Issue by ackerdev** [jccguimaraes/atom-project-viewer#90]
I would like the project search field to be empty when I open the project switcher, so that I don't have to clear the field before I can start typing in the project's name.

Currently it leaves the last entry in the search field, meaning that if opened `foo` earlier and I want to switch to `bar`, I have to select all and delete before I can start typing `bar`.

**Comment by jccguimaraes** [comment]
hey again @ackerdev,

my bad :dagger: 
will try to add it in `0.3.x` version!

Thanks for the great feedback.

**Comment by jccguimaraes** [comment]
Just release `0.3.26`. Can you check this out please?

**Comment by ackerdev** [comment]
Just updated, looks all good here. Thanks for your work on this 😄
