### ISSUE TITLE
Beautify project-viewer.json

### ISSUE THREAD

**Issue by jerone** [jccguimaraes/atom-project-viewer#91]
# ISSUE

All projects are stored on _one line_ in the file `project-viewer.json`, making reading and altering that file very difficult. I would like to propose an option to beautify the content of that file.

**Comment by jccguimaraes** [comment]
Hi @jerone,

This file is actually being stored by atom itself, so even if you beautify it, it will go back to a stringified version of it.

**Comment by jerone** [comment]
Yeah I had a suspicion that was the [case](https://github.com/jccguimaraes/atom-project-viewer/blob/346a06a4c5d4e01b7b73bf62cfc31b94bf3bbcae/src/db.js#L235).

The use-case for a more used storage location (`~/.atom` root) is probably very limited?

**Comment by jccguimaraes** [comment]
initially it was on the `~/.atom` but for this matter, i needed to make the workflow of `rw` and it was buggy when Atom crashed an all. So I decided to go with the _native_ api, so at least the file would not be corrupted. But `storeSync` / `load`, only fetches from the `storage` folder.

This situation created the ability to save it to the "cloud" (private gist).

I can't find any safe bet for it :disappointed: 

You are more than welcome to give your feedback.

PS: I am working on a new version (`0.4.0`) it would be nice for some external insight. (check [here](https://github.com/jccguimaraes/atom-project-viewer/blob/0.4.0/src/_database.js) the development if you want. There is a lot of crap there at the moment.

**Comment by jerone** [comment]
[**@jccguimaraes**](https://github.com/jccguimaraes) commented on [2 nov. 2016 01:15 CET](https://github.com/jccguimaraes/atom-project-viewer/issues/91#issuecomment-257737451 "2016-11-02T00:15:45Z - Replied by Github Reply Comments"):
> initially it was on the `~/.atom` but for this matter, i needed to make the workflow of `rw` and it was buggy when Atom crashed an all. So I decided to go with the _native_ api, so at least the file would not be corrupted. But `storeSync` / `load`, only fetches from the `storage` folder.
> 
> This situation created the ability to save it to the "cloud" (private gist).
>
> I can't find any safe bet for it
> 
> You are more than welcome to give your feedback.

I actually use [Sync Settings](http://atom.io/packages/sync-settings) package to back-up the `storage\project-viewer.json` file to a gist. Because the content is an one-liner, comparison is more difficult. But I understand your situation and will close this issue.

The only thing to watch for is that `getStorageFolder()` [isn't a public](https://atom.io/docs/api/search/latest?utf8=%E2%9C%93&q=getStorageFolder) method.


> PS: I am working on a new version (`0.4.0`) it would be nice for some external insight. (check [here](https://github.com/jccguimaraes/atom-project-viewer/blob/0.4.0/src/_database.js) the development if you want. There is a lot of crap there at the moment.

Hopefully I have some spare time next week. I see you've defined some sort of [roadmap](https://github.com/jccguimaraes/atom-project-viewer/blob/0.4.0/FEATURES.md).
