### ISSUE TITLE
FEATURE: Override configuration by project

### ISSUE THREAD

**Issue by dsoares** [jccguimaraes/atom-project-viewer#92]
# Override configuration by project

First of all, thank you for this package! :)

This is half a question, half a feature request. I would like to know if this package accepts overriding Atom configuration by project (like project-manager). 
Something like:

```cson
(... client and group stuff ...)
"projects": 
  0:
    name: "my_project_name"
    icon: ""
    paths: [ "my_poject_paths" ]
    dev: false
    settings:
      "*":
        editor:
          tabLength: 2
        "php-cs-fixer":
          executeOnSave: false
```

Am i able to add that `settings` property to a project, to override the global Atom configuration (even if i added it manually to the JSON config file of project-viewer) ? 
For example, i use `tabLength=4` in general but for a particular project i must use `tabLength=2`.

## Environment

Any.

**Comment by jccguimaraes** [comment]
hi @dsoares,

Thanks for the kind words, that's what keeps me going.

Currently i am doing an enormous change on the package, implementing a lot of new stuff, dropping other things.
This runner to a feature is interested, but does it not make sense to just use a `.editorconfig` file for each project?

either way, i would investigate this addon to the settings.

I am investing a lot of time in how this package keeps track of all the configurations.

I will keep in touch

**Comment by dsoares** [comment]
Hi,
I didn't know `.editorconfig`, it will work. Although this will be one more dot file in the project root directory.. I would rather put it in my Atom configuration, since it is only related with Atom. 

But since `.editorconfig` can do the job, keep the very nice work here implementing the new features! Maybe in the future, you'll think about it ;)

**Comment by jccguimaraes** [comment]
you bet!!!

**Comment by brewster1134** [comment]
Being able to have project specific atom configuration is keeping me from swithing from project-manager.  the linting is fine to use editorconfig, but i mainly depend on being able to specify the `IgnoredNames` array. I cant always rely on just ignoring files in version control, and they will vary drastically across various project types (AEM, Java, JS, etc)

I would be very interested in knowing if/when custom atom configurations per project is coming down the pipes! :)

**Comment by jccguimaraes** [comment]
hi @brewster1134, i will make an investigation to this feature as at least you and @dsoares are keen to this

**Comment by jccguimaraes** [comment]
Hey @dsoares and @brewster1134,

So I have been digging and I have only found a way to make this work.

1. backup current editor settings
2. each project sets it's own rules
3. new projects inherits from the backup settings
4. possibility to revert individual projects to the backup or all projects

Any feedback?

**Comment by brewster1134** [comment]
not sure i follow...
do you mean as you load a project, it swaps out the core config.cson editor settings?  it would probably be pretty dangerous and problematic to do anything with the core config aside from read-only.

IMO the ideal approach would be either unique settings file for each project that the global config.cson is reverse-merged into and loaded.  

project-manager does with a `projects.cson` file that holds configuration for all the projects, so i would be curious how they are doing... but having said that, i have always found it to be a bit buggy with settings not being applied unless you re-open or refresh the project. i havent done any atom development, but i will try to look into the project manager source and the atom dev api a bit.

also a possible reference could be sublime text. they have project management baked into the app itself, and it works really well.  project management was the big feature gap between atom and sublime, so it would be pretty valuable to have a solid working solution in atom.

**Comment by jccguimaraes** [comment]
As said in the slack channel of atom **"There isn't a project-specific configuration convention in Atom right now"**.

But if you are interested in contributing be my guest, you are more than welcome to do that!
I think it overrides the core config also...
