### ISSUE TITLE
Fix: Missing DEV Icons

### ISSUE THREAD

**Issue by tuanquynh0508** [jccguimaraes/atom-project-viewer#93]
# ISSUE
Hi !. I missing icons dev in my Atom

## Environment
- **OS**: Ubuntu 16.10;
- **Atom**: 1.11.2;
- **Project Viewer**: 0.3.25;
- Any other particularity;

## Steps
Please try to describe **step by step** how to get to the issue.

**Comment by jccguimaraes** [comment]
hi @tuanquynh0508,

This is because i am using latest for the devicons and octicons package and they changed the structure.
Will try to make it work again sorry for this.

**Comment by tuanquynh0508** [comment]
Hi @gitmagic-bot : Sorry because first time I post issue. I will format better for next time. Thanks.
Hi @jccguimaraes: Thanks you.

**Comment by jccguimaraes** [comment]
Just release `0.3.26`. Can you check this out please?

**Comment by tuanquynh0508** [comment]
@jccguimaraes I just update latest version, everything work well. Thank you very much!.
