### ISSUE TITLE
ISSUE: shortcuts are not working using Windows

### ISSUE THREAD

**Issue by lneveu** [jccguimaraes/atom-project-viewer#94]
# ISSUE
Hi,
I just realized that shortcuts don't work with Windows :o **cmd** key does not exist.
And it's probably the same with Linux environment. You should try to adapt shortcuts according to environments?
Like:

```
'.platform-darwin':
  'cmd-alt-v' : 'project-viewer:toggle-select-view'

'.platform-win32, .platform-linux':
  'ctrl-alt-v' : 'project-viewer:toggle-select-view'
```

Thx :)

## Environment
- **OS**: Windows 10;
- **Atom**: 1.12.0;

**Comment by jccguimaraes** [comment]
hey @lneveu thanks! my bad :+1: 

let me see if i can make if available tomorrow, fixing some anoying bugs from 3rd party deps...

**Comment by jccguimaraes** [comment]
@lneveu o.O what version of the package you are using?

latest version uses the following keymaps

```
{
  ".platform-darwin, .platform-win32, .platform-linux": {
      "ctrl-alt-cmd-v": "project-viewer:toggle-select-view",
      "ctrl-alt-cmd-b": "project-viewer:toggle-display",
      "ctrl-alt-cmd-n": "project-viewer:toggle-focus"
  }
}
```

Can you validate this for me?

**Comment by lneveu** [comment]
(I'm using the last version of the package at home, but at work I'm still with the 0.2.34 because of this issue #76 ^^)
Sorry, I misspoke :/ It was just an example of how you can (maybe?) fix this issue.
Here, the full keymaps that I have changed to match with my usage:

```
{
  ".platform-darwin": {
    "cmd-alt-v": "project-viewer:toggle-select-view",
    "cmd-alt-b": "project-viewer:toggle-display",
    "cmd-alt-n": "project-viewer:toggle-focus"
  },
  ".platform-win32, .platform-linux": {
    "ctrl-alt-v": "project-viewer:toggle-select-view",
    "ctrl-alt-b": "project-viewer:toggle-display",
    "ctrl-alt-n": "project-viewer:toggle-focus"
  }
}
```
I let you try if it's ok for you? Or if you want to change keys or something.

**Comment by jccguimaraes** [comment]
:tophat: sir

**Comment by jccguimaraes** [comment]
i have mapped for the `1.0.0` release the following combinations:

`shift-ctrl-alt-<x>` do you feel comfortable with this?

**Comment by lneveu** [comment]
Thx!
Maybe those combinations are not "very handy" to be easily used but, as you mentioned it, there are so much packages and the number of keys is limited ^^
Anyway, people can re-map the commands with their own shortcuts using the keymap.cson file if they want 😄 
(in my case, I'll certainly re-map them with `shift-ctrl-<x>` 😛 )

**Comment by jccguimaraes** [comment]
Just release `0.3.26`. Can you check this out please?

**Comment by lneveu** [comment]
Thank you! All seems good! (and don't forget to update README.md file with updated shortcuts 👍 )

**Comment by jccguimaraes** [comment]
Good catch, just updated. Will close this then!
