### ISSUE TITLE
Fix: Clients/Projects getting mixed up

### ISSUE THREAD

**Issue by eduardomart** [jccguimaraes/atom-project-viewer#96]
# ISSUE
I added a new project to a new client and it didn't appear under the client, I restarted atom and now all my projects are under the wrong client.

## Environment
- **OS**: macOS Sierra 10.12.1
- **Atom**: 1.12.3

**Comment by jccguimaraes** [comment]
@eduardomart thanks for reporting this,

Let me take a look at this!

**Comment by eduardomart** [comment]
Maybe this notification can be of some help, it appears everytime I reopen Atom now:

![screen shot 2016-11-17 at 2 03 24 pm](https://cloud.githubusercontent.com/assets/1833020/20409500/bb200d40-acce-11e6-844e-c14726e0dd69.png)

**Comment by jccguimaraes** [comment]
this message is because the old file structure no longer exists and if you don't want to be warned again for this attempt to migrate old data to the current one. go to package settings and untick `Convert Old Data`.

Regarding the actual issue here, still investigating

**Comment by jccguimaraes** [comment]
I have tried to follow your steps.

1. `Convert Old Data` is set to true, so i have that notification every time
2. I don't have any Clients / Groups or Projects created.
3. I create a new Client
4. I create a new project within the new Client
5. I create a another new Client
6. Restart and everything is as expected

Is this the current process for you?

**Comment by eduardomart** [comment]
I just went thru them and here's all I could find out, a couple of clients had projects under them, which were correctly set before, but for some reason the client tag wasn't highlighted when I went to 'update' them, I don't know how this happened so I am not sure I can tell you the steps to recreate the issue. I do know Atom updated to 1.12.3 before this happened though.

**Comment by jccguimaraes** [comment]
can we close this and if the problem occurs again we try to deal with it again @eduardomart?

**Comment by eduardomart** [comment]
Sounds good. Thanks!

**Comment by eduardomart** [comment]
So I am having this issue again

All projects are gone and every time I restart Atom I get this:
![screen shot 2017-02-13 at 10 13 31 pm](https://cloud.githubusercontent.com/assets/1833020/22917468/f0b9e13c-f239-11e6-8e6b-a79e6dd4d21d.png)

**Comment by eduardomart** [comment]
Sorry I see it now, I was going to Atom > Packages > Project Manager instead of the Packages menu. I think that did fix it.
